### ISSUE TITLE
Cannot install OctoBot on Mac

### ISSUE THREAD

**Issue by r-hou** [Drakkar-Software/OctoBot#1091]
## Step 1: Describe your environment
  * OS : OSX 10.15.3
  * Python Version: 3.7.1

 
## Step 2: Describe the problem:
I started the app from launcher_app_osx. Once I installed OctoBot from the webpage. The terminal returned the erorr as following. Actually I could find binary file "OctoBot" in my directory. Then I tried `chmod +x OctoBot` but it didn't work and returned the error "exec format error: ./OctoBot". Then I tried to get the url of the binary file download the binary file manually. However, the file I downloaded from the web is named as OctoBot_linux, so I guessed that  you had wrongly uploaded the binary file which is built on Linux OS not on Mac OS. If you have any idea about this please let me know. Thank you very much!

ERROR:launcher:Exception on /bot [GET]
Traceback (most recent call last):
  File "flask/app.py", line 2446, in wsgi_app
  File "flask/app.py", line 1951, in full_dispatch_request
  File "flask/app.py", line 1820, in handle_user_exception
  File "flask/_compat.py", line 39, in reraise
  File "flask/app.py", line 1949, in full_dispatch_request
  File "flask/app.py", line 1935, in dispatch_request
  File "/Users/hourui/Downloads/octo/launcher/app/app_controller.py", line 39, in bot
    local_version = OctoBotVersion().get_current_version()
  File "/Users/hourui/Downloads/octo/launcher/tools/version.py", line 83, in get_current_version
    return executor.execute_command_on_current_binary(binary_path, ["--version"]).split("\r\n")[0]
  File "/Users/hourui/Downloads/octo/launcher/tools/executor.py", line 26, in execute_command_on_current_binary
    return subprocess.Popen(cmd, stdout=PIPE).stdout.read().rstrip().decode()
  File "subprocess.py", line 775, in __init__
  File "subprocess.py", line 1522, in _execute_child
OSError: [Errno 8] Exec format error: './OctoBot'

**Comment by Herklos** [comment]
HI @r-hou, I you already have python 3.7 installed I suggest you install OctoBot with [python](https://github.com/Drakkar-Software/OctoBot/wiki/With-Python-only) or with [pip](https://github.com/Drakkar-Software/OctoBot/wiki/With-PIP). OctoBot on MAC binary is not maintened anymore.
