### ISSUE TITLE
Why my win7 can't install and update the latest version of OctoBot

### ISSUE THREAD

**Issue by TopSun2010** [Drakkar-Software/OctoBot#1176]
Why my win7 can't install and update the latest version of OctoBot.
I still use OctoBot-launcher V2.0.3 and BOT v0.3.6
When I upgrade, my cmd will report an error: urllib.error.URLError: <urlopen error [WinError 10061]
like this:
ERROR:launcher:Exception on /install [GET]
Traceback (most recent call last):
  File "urllib\request.py", line 1317, in do_open
  File "http\client.py", line 1244, in request
  File "http\client.py", line 1290, in _send_request
  File "http\client.py", line 1239, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 966, in send
  File "http\client.py", line 1406, in connect
  File "http\client.py", line 938, in connect
  File "socket.py", line 727, in create_connection
  File "socket.py", line 716, in create_connection
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\flask\app.py", line 2446, in wsgi_app
  File "site-packages\flask\app.py", line 1951, in full_dispatch_request
  File "site-packages\flask\app.py", line 1820, in handle_user_exception
  File "site-packages\flask\_compat.py", line 39, in reraise
  File "site-packages\flask\app.py", line 1949, in full_dispatch_request
  File "site-packages\flask\app.py", line 1935, in dispatch_request
  File "N:\bot\launcher\app\app_controller.py", line 68, in install
    launcher_instance.update_bot(launcher_module.bot_instance)
  File "N:\bot\launcher\app\launcher_app.py", line 94, in update_bot
    environment.install_bot(force_package=force_package)
  File "N:\bot\launcher\tools\environment.py", line 104, in install_bot
    create_environment()
  File "N:\bot\launcher\tools\environment.py", line 95, in create_environment
    ensure_file_environment(INSTALL_DOWNLOAD)
  File "N:\bot\launcher\tools\environment.py", line 148, in ensure_file_environm
ent
    urllib.request.urlretrieve(file_to_dl[0], file_name)
  File "urllib\request.py", line 247, in urlretrieve
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 543, in _open
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 1360, in https_open
  File "urllib\request.py", line 1319, in do_open
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，
无法连接。>
INFO:werkzeug:172.34.255.27 - - [12/May/2020 09:41:54] "GET /install HTTP/1.1" 5
00 -
INFO:werkzeug:172.34.255.27 - - [12/May/2020 09:41:56] "GET /bot HTTP/1.1" 200 -

**Comment by Herklos** [comment]
Hi TopSun, thanks for your interest on OctoBot. It seems that your computer can't connect to github.com. Can you check your proxy settings? Github could also have ban your ip for some reason.

**Comment by TopSun2010** [comment]
really glad to receive your response
I have tried to update using Alibaba Cloud server, but it is not available.
I will try another cloud server.

**Comment by Herklos** [comment]
Any updates @TopSun2010 ?
