### ISSUE TITLE
Webinterface Error after changing Config 0.4.0

### ISSUE THREAD

**Issue by ChristianFeldmannHamm** [Drakkar-Software/OctoBot#1282]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment
  * OS : Debian
  * Python Version: 3.7.3
  * In case you are not using a binary version:
    * Branch: 0.4.0
    * Last Commit ID: a20
 
## Step 3: Describe the problem:
**Describe the bug**
Stays in loading screen.

### Steps to reproduce:

  1. Start Bot
  2. Change and Save Configuration
  3. Restart
  
### Observed Results:

  * Home, trading and portfolio page in endless loading screen

### Relevant code exceptions or logs:
Message in event log:

2020-08-13 21:05:27 | ERROR | WebInterface | Error with websocket: must be real number, not NoneType
-- | -- | -- | --

// paste your log here
2020-08-13 21:05:39,326 ERROR    WebInterface         must be real number, not NoneType
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 696, in _handle_event
    ret = handler()
  File "/home/OctoBot/tentacles/Services/Interfaces/web_interface/websockets/abstract_websocket_namespace_notifier.py", line 53, in wrapped
    return func(self, *args, **kwargs)
  File "/home/OctoBot/tentacles/Services/Interfaces/web_interface/websockets/dashboard.py", line 106, in on_connect
    self.on_profitability()
  File "/home/OctoBot/tentacles/Services/Interfaces/web_interface/websockets/abstract_websocket_namespace_notifier.py", line 53, in wrapped
    return func(self, *args, **kwargs)
  File "/home/OctoBot/tentacles/Services/Interfaces/web_interface/websockets/dashboard.py", line 73, in on_profitability
    emit("profitability", self._get_profitability())
  File "/home/OctoBot/tentacles/Services/Interfaces/web_interface/websockets/dashboard.py", line 40, in _get_profitability
    profitability_digits)
  File "octobot_commons/pretty_printer.py", line 192, in octobot_commons.pretty_printer.round_with_decimal_count
TypeError: must be real number, not NoneType
 2020-08-13 21:05:39,327 ERROR    WebInterface         Error with websocket: must be real number, not NoneType

**Comment by GuillaumeDSM** [comment]
Hi @ChristianFeldmannHamm !
Indeed, thanks for the issue, it will be fixed when https://github.com/Drakkar-Software/OctoBot-Commons/pull/102 will be merged You will then be able to get the fix by updating your OctoBot-Commons lib or with the next OctoBot version.

**Comment by GuillaumeDSM** [comment]
It's now merged, `python -m pip install -U OctoBot-Commons` should fix this

**Comment by ChristianFeldmannHamm** [comment]
Great work, thank you very much.
