### ISSUE TITLE
ArbitrageTradingMode different errors

### ISSUE THREAD

**Issue by ChristianFeldmannHamm** [Drakkar-Software/OctoBot#1290]
## Step 1: Have you search for this issue before posting it?

Yes, found nothing.

## Step 2: Describe your environment
  * OS : Raspberry Pi 4
  * Python Version: 3.7.3
  * In case you are not using a binary version:
    * Branch: 0.4.0a20
 
## Step 3: Describe the problem:
**Describe the bug**
I have activated the ArbitrageTradingMode, specified two exchanges and selected the mode "Trade in exchange sandbox". After that I got several errors.
After I deactivated the mode, only errors on not supported currency pairs.

### Relevant code exceptions or logs:
 
![2020-08-15 23_27_56-Window](https://user-images.githubusercontent.com/23531655/90322106-7ca83e80-df50-11ea-8ec5-cbcde5c1421b.png)
![2020-08-15 23_28_52-Window](https://user-images.githubusercontent.com/23531655/90322107-7d40d500-df50-11ea-8355-e3fbf7a31cd5.png)
![2020-08-15 23_28_35-Window](https://user-images.githubusercontent.com/23531655/90322108-7d40d500-df50-11ea-8380-a1ea47b3dac6.png)
![2020-08-15 23_28_17-Window](https://user-images.githubusercontent.com/23531655/90322109-7dd96b80-df50-11ea-88cb-3d552ec565da.png)
![2020-08-15 23_28_09-Window](https://user-images.githubusercontent.com/23531655/90322110-7dd96b80-df50-11ea-91f2-8be83e50ef16.png)

// paste your log here

 2020-08-15 22:22:34,605 DEBUG    OctoBot Channel      OCTOBOT_CHANNEL : SUBJECT = notification || ACTION = start_service_feed || DATA = {'successful_operation': True}
 2020-08-15 22:22:34,605 DEBUG    OctoBot Channel      OCTOBOT_CHANNEL : SUBJECT = notification || ACTION = start_service_feed || DATA = {'successful_operation': True}
 2020-08-15 22:22:34,606 DEBUG    OctoBot Channel      OCTOBOT_CHANNEL : SUBJECT = notification || ACTION = start_service_feed || DATA = {'successful_operation': True}
 2020-08-15 22:22:39,565 DEBUG    RecentTradeUpdater[kucoin] Pausing...
 2020-08-15 22:23:18,491 ERROR    WebInterface         must be real number, not NoneType
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/flask_socketio/__init__.py", line 696, in _handle_event
    ret = handler()
  File "/home/pi/OctoBot/tentacles/Services/Interfaces/web_interface/websockets/abstract_websocket_namespace_notifier.py", line 53, in wrapped
    return func(self, *args, **kwargs)
  File "/home/pi/OctoBot/tentacles/Services/Interfaces/web_interface/websockets/dashboard.py", line 106, in on_connect
    self.on_profitability()
  File "/home/pi/OctoBot/tentacles/Services/Interfaces/web_interface/websockets/abstract_websocket_namespace_notifier.py", line 53, in wrapped
    return func(self, *args, **kwargs)
  File "/home/pi/OctoBot/tentacles/Services/Interfaces/web_interface/websockets/dashboard.py", line 73, in on_profitability
    emit("profitability", self._get_profitability())
  File "/home/pi/OctoBot/tentacles/Services/Interfaces/web_interface/websockets/dashboard.py", line 40, in _get_profitability
    profitability_digits)
  File "octobot_commons/pretty_printer.py", line 192, in octobot_commons.pretty_printer.round_with_decimal_count
TypeError: must be real number, not NoneType
 2020-08-15 22:23:18,494 ERROR    WebInterface         Error with websocket: must be real number, not NoneType

[OctoBot.log](https://github.com/Drakkar-Software/OctoBot/files/5079526/OctoBot.log)

**Comment by Herklos** [comment]
Hi @ChristianFeldmannHamm, thanks for the report. We already identified this issue and we fixed it in development version. This fix will be available in the next release in few days.
