### ISSUE TITLE
Error while Docker installation

### ISSUE THREAD

**Issue by ChristianFeldmannHamm** [Drakkar-Software/OctoBot#1291]
## Step 1: Have you search for this issue before posting it?

Yes, found nothing.

## Step 2: Describe your environment
  * OS : Debian 10
  * Python Version: 3.7.3
  * In case you are not using a binary version:
    * Branch: 0.4.0
    * Clean installation
 
## Step 3: Describe the problem:
**Describe the bug**
While executing `octobot_cli start --docker` installation fails.

### Steps to reproduce:

  1. Clean installation
  2. OctoBot installation as mentioned on GitHub
  3. _____
 

### Relevant code exceptions or logs:
 
root@31c38e2d:/home# octobot_cli start --docker
2020-08-17 06:27:50,897 - Anonymous - INFO - Creating OctoBot container...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/create?name=octobot

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/octobot_cli", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/octobot_cli/cli.py", line 114, in cli
    args.func(args, octobot_args + to_restore_args)
  File "/usr/local/lib/python3.7/dist-packages/octobot_cli/manager.py", line 40, in start_octobot
    octobot_docker.start_octobot(octobot_args)
  File "/usr/local/lib/python3.7/dist-packages/octobot_cli/octobot_docker.py", line 157, in start_octobot
    use_arm_image=use_arm_image)
  File "/usr/local/lib/python3.7/dist-packages/octobot_cli/octobot_docker.py", line 130, in _run_on_octobot_container
    args=args)
  File "/usr/local/lib/python3.7/dist-packages/octobot_cli/octobot_docker.py", line 76, in _run_octobot_container
    {'bind': '/bot/octobot/tentacles', 'mode': 'rw'}
  File "/usr/local/lib/python3.7/dist-packages/docker/models/containers.py", line 803, in run
    detach=detach, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/docker/models/containers.py", line 861, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.7/dist-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.7/dist-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.7/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Conflict. The container name "/octobot" is already in use by container "1da954a8a533c0b362d550e68350110ce0f785c22b152bd0e8050b9ced0033db". You have to remove (or rename) that container to be able to reuse that name.")
root@31c38e2d:/home#

**Comment by Herklos** [comment]
Hi @ChristianFeldmannHamm, `"Conflict. The container name "/octobot" is already in use by container` you may already have a running Octobot. You can check by using `docker ps`.

**Comment by ChristianFeldmannHamm** [comment]
I'll test it when I get home. But was a complete reinstallation of the whole system.

**Comment by ChristianFeldmannHamm** [comment]
Doesn't work for me. No docker image active.

root@31c38e2d:~# octobot_cli start --docker
2020-08-17 15:21:41,406 - Anonymous - INFO - Creating OctoBot container...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/create?name=octobot

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/octobot_cli", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/octobot_cli/cli.py", line 114, in cli
    args.func(args, octobot_args + to_restore_args)
  File "/usr/local/lib/python3.7/dist-packages/octobot_cli/manager.py", line 40, in start_octobot
    octobot_docker.start_octobot(octobot_args)
  File "/usr/local/lib/python3.7/dist-packages/octobot_cli/octobot_docker.py", line 157, in start_octobot
    use_arm_image=use_arm_image)
  File "/usr/local/lib/python3.7/dist-packages/octobot_cli/octobot_docker.py", line 130, in _run_on_octobot_container
    args=args)
  File "/usr/local/lib/python3.7/dist-packages/octobot_cli/octobot_docker.py", line 76, in _run_octobot_container
    {'bind': '/bot/octobot/tentacles', 'mode': 'rw'}
  File "/usr/local/lib/python3.7/dist-packages/docker/models/containers.py", line 803, in run
    detach=detach, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/docker/models/containers.py", line 861, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.7/dist-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.7/dist-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.7/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Conflict. The container name "/octobot" is already in use by container "1da954a8a533c0b362d550e68350110ce0f785c22b152bd0e8050b9ced0033db". You have to remove (or rename) that container to be able to reuse that name.")
root@31c38e2d:~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@31c38e2d:~#

**Comment by ChristianFeldmannHamm** [comment]
Error found `docker ps -a` showed it as inactive. Command `docker start <id>` made it working again. THX.
