### ISSUE TITLE
Portfolio Error with Bitfinex

### ISSUE THREAD

**Issue by Sascha321** [Drakkar-Software/OctoBot#1297]
Ubuntu 20.04
OctoBot 0.3.9
Nodes.js 10.19.0

If I include "Bitfinex" under Exchanges, then I can no longer open the portfolio and the following error message appears:

> 2020-08-23 21:04:23	ERROR	asyncio_tools	<coroutine object TradesManager.update_portfolio_and_currencies_current_value at 0x7fe3a850d848> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: None)
2020-08-23 21:04:22	ERROR	asyncio_tools	<coroutine object TradesManager.update_portfolio_and_currencies_current_value at 0x7fe3a8505e48> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: None)
2020-08-23 21:04:22	ERROR	asyncio_tools	<coroutine object TradesManager.update_portfolio_and_currencies_current_value at 0x7fe3a850dec8> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: None)
2020-08-23 21:03:59	ERROR	asyncio_tools	<coroutine object TradesManager.update_portfolio_and_currencies_current_value at 0x7fe3a85821c8> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: None)
2020-08-23 21:03:50	ERROR	asyncio_tools	<coroutine object TradesManager.update_portfolio_and_currencies_current_value at 0x7fe3a8502248> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: None)
2020-08-23 21:03:29	ERROR	asyncio_tools	<coroutine object TradesManager.get_profitability at 0x7fe3a8505748> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: None)
2020-08-23 21:03:29	ERROR	TradesManager[bitfinex]	
2020-08-23 20:59:25	ERROR	asyncio_tools	<coroutine object TradesManager.update_portfolio_and_currencies_current_value at 0x7fe3a8576548> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: None)
2020-08-23 20:59:15	ERROR	asyncio_tools	<coroutine object TradesManager.update_portfolio_and_currencies_current_value at 0x7fe3a85797c8> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: None)
2020-08-23 20:59:10	ERROR	asyncio_tools	<coroutine object TradesManager.update_portfolio_and_currencies_current_value at 0x7fe3a85763c8> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: None)
2020-08-23 20:58:17	ERROR	asyncio_tools	<coroutine object TradesManager.update_portfolio_and_currencies_current_value at 0x7fe3a84fa848> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: None)
2020-08-23 20:57:48	ERROR	asyncio_tools	<coroutine object TradesManager.update_portfolio_and_currencies_current_value at 0x7fe3a850ad48> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: None)
2020-08-23 20:13:16	ERROR	asyncio_tools	<coroutine object TradesManager.get_profitability at 0x7fe3a84fa1c8> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: None)
2020-08-23 20:13:16	ERROR	TradesManager[bitfinex]	
> 

Is Bitfinex not supported?

**Comment by GuillaumeDSM** [comment]
Hi @Sascha321, is the issue also appearing when selecting bitfinex2 ?

**Comment by Sascha321** [comment]
Hello GuillaumeDSM, when I add bitfinanex2, OctoBot no longer starts. I get the following error message:

> 
Traceback (most recent call last):
  File "tools/commands.py", line 111, in start_bot
  File "core/octobot.py", line 72, in start
  File "core/task_manager.py", line 57, in start_tasks
  File "trading/trader/trader.py", line 106, in launch
  File "trading/trader/trader.py", line 426, in update_open_orders
  File "trading/exchanges/exchange_dispatcher.py", line 231, in get_open_orders
  File "trading/exchanges/rest_exchanges/rest_exchange.py", line 196, in get_open_orders
Exception: This exchange doesn't support fetchOpenOrders
 2020-08-24 06:42:16,574 ERROR    root                   File "start.py", line 295, in <module>
  File "start.py", line 291, in main
  File "start.py", line 199, in start_octobot
  File "asyncio/runners.py", line 43, in run
  File "asyncio/base_events.py", line 584, in run_until_complete
  File "tools/commands.py", line 122, in start_bot
  File "tools/commands.py", line 111, in start_bot
  File "core/octobot.py", line 72, in start
  File "core/task_manager.py", line 57, in start_tasks
  File "trading/trader/trader.py", line 106, in launch
  File "trading/trader/trader.py", line 426, in update_open_orders
  File "trading/exchanges/exchange_dispatcher.py", line 231, in get_open_orders
  File "trading/exchanges/rest_exchanges/rest_exchange.py", line 196, in get_open_orders
NoneType: None
 2020-08-24 06:42:16,575 ERROR    root                 <class 'Exception'>: This exchange doesn't support fetchOpenOrders
NoneType: None

>

**Comment by Sascha321** [comment]
I don't know exactly why, but sometimes the portfolio opens after about 30 seconds.
When I click on the "Home" tab, I get the following message:
> 
.09037228619152463}}
 2020-08-24 12:47:53,394 ERROR    interfaces.web       Exception on /dashboard/currency_price_graph_update/binance/BTC|USD/1h/live [POST]
Traceback (most recent call last):
  File "site-packages/flask/app.py", line 2447, in wsgi_app
  File "site-packages/flask/app.py", line 1952, in full_dispatch_request
  File "site-packages/flask/app.py", line 1821, in handle_user_exception
  File "site-packages/flask/_compat.py", line 39, in reraise
  File "site-packages/flask/app.py", line 1950, in full_dispatch_request
  File "site-packages/flask/app.py", line 1936, in dispatch_request
  File "interfaces/web/controllers/dashboard.py", line 33, in currency_price_graph_update
  File "interfaces/web/models/dashboard.py", line 200, in get_currency_price_graph_update
  File "evaluator/symbol_evaluator.py", line 202, in get_evaluator_task_managers
KeyError: 'binance'

>

**Comment by Sascha321** [comment]
Hello, I have Octobot 3.9 running on a Raspbery pi 3, the portfolio doesn't crash there, but it takes a long time to load. Somehow it has to do with Bitfinex. As soon as I take this Exchnager out, the portfolio opens up again quickly.
