### ISSUE TITLE
trades history

### ISSUE THREAD

**Issue by Sascha321** [Drakkar-Software/OctoBot#1299]
Hello, 
where can you turn on the trades history? it is always empty for me, can that be?

greetings sascha

**Comment by GuillaumeDSM** [comment]
Hi @Sascha321 !
On OctoBot 0.3, trade history is only the history of the current session.
On OctoBot 0.4 (currenty in beta), this history also contains previous sessions when connected to an exchange account.

**Comment by Sascha321** [comment]
Hello GuillaumeDSM, thank you for your feedback.
Where can I then see if I have successful transactions? do I only see this with my broker?
Has the Kraken broker already been implemented? I get a captcha error message in the log.

**Comment by GuillaumeDSM** [comment]
On 0.3 they appear in trade history (successful transactions from the current octobot instance).
Kraken has not been tested yet on 0.3, it's one of the exchanges we will add in 0.4

**Comment by Sascha321** [comment]
Hello, I can't find any closed trades, weird.
in which directory are the logs? "../logs"?
I have already understood correctly that there is no history in the Webgui in 0.3

**Comment by GuillaumeDSM** [comment]
Logs are in the logs directory yes.
It's weird indeed, are you sure your bot made trades in your current instance ?

**Comment by Sascha321** [comment]
I really don't know if I made trades, I think I found 2 at Coinbase.
I noticed another bug there. If you click directly on the symbol of the crypto currency in trading "Market status" you will see the graph of the crypto currency. The symbol is always stored with the Trader Binance, and so you get the following error message in the log if there is nothing to display.
Is it actually OK if I show you the error messages here?

> 
 2020-08-26 17:11:07,021 ERROR    interfaces.web       Exception on /dashboard/currency_price_graph_update/binance/BTC|USD/5m/live [POST]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/OctoBot/interfaces/web/controllers/dashboard.py", line 33, in currency_price_graph_update
    backtesting=backtesting))
  File "/home/pi/OctoBot/interfaces/web/models/dashboard.py", line 200, in get_currency_price_graph_update
    exchange_list[exchange])
  File "/home/pi/OctoBot/evaluator/symbol_evaluator.py", line 202, in get_evaluator_task_managers
    return self.evaluator_task_managers[exchange.get_name()]
KeyError: 'binance'
>

**Comment by GuillaumeDSM** [comment]
Yes please, post your errors here, it will help to identify problems.

Thanks for the issue report on the web interface, this issue is fixed in 0.4 !

Trades will also appear on the home screen as red and green dots. as in backtesting

**Comment by Sascha321** [comment]
Hello

Most of my trades or pairings are canceled. Is this due to the attitudes or the fluctuations in the rate of the crypto currency?
> 
octo-bot08121971, [27.08.20 00:15]
[Real Trader] Order(s) creation 
- BUY_LIMIT: 0.12653 ETH at 381.59 USDT  binance 08-27 00:15

octo-bot08121971, [27.08.20 02:55]
[Real Trader] Order(s) canceled :
- BUY_LIMIT: 0.12634 ETH at 382.14 USDT  binance 08-26 23:50

octo-bot08121971, [27.08.20 02:55]
[Real Trader] Order(s) canceled :
- BUY_LIMIT: 0.12653 ETH at 381.59 USDT  binance 08-27 00:15

octo-bot08121971, [27.08.20 02:55]
[Real Trader] Order(s) creation 
- BUY_LIMIT: 0.12629 ETH at 382.25 USDT  binance 08-27 02:55

octo-bot08121971, [27.08.20 03:10]
[Real Trader] Order(s) canceled :
- BUY_LIMIT: 0.12629 ETH at 382.25 USDT  binance 08-27 02:55

octo-bot08121971, [27.08.20 03:10]
[Real Trader] Order(s) creation 
- BUY_LIMIT: 0.12654 ETH at 381.68 USDT  binance 08-27 03:10

octo-bot08121971, [27.08.20 04:00]
[Real Trader] Order(s) creation 
- STOP_LOSS: 0.11750232 ETH at 0.03267 BTC  coinbasepro 08-27 04:00
- SELL_LIMIT: 0.11750232 ETH at 0.03429 BTC  coinbasepro 08-27 04:00

octo-bot08121971, [27.08.20 04:20]
[Real Trader] Order(s) canceled :
- STOP_LOSS: 0.11750232 ETH at 0.03267 BTC  coinbasepro 08-27 04:00
- SELL_LIMIT: 0.11750232 ETH at 0.03429 BTC  coinbasepro 08-27 04:00

octo-bot08121971, [27.08.20 05:25]
[Real Trader] Order(s) canceled :
- BUY_LIMIT: 0.12654 ETH at 381.68 USDT  binance 08-27 03:10

octo-bot08121971, [27.08.20 05:28]
[Real Trader] Order(s) canceled :
- BUY_LIMIT: 0.1275 ETH at 378.79 USDT  binance 08-27 05:25
>

**Comment by Sascha321** [comment]
I keep getting the following error messages
> 
 2020-08-27 05:16:43,827 ERROR    asyncio_tools        <coroutine object TradesManager.get_profitability at 0x6c46b030> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: None)
 2020-08-27 05:16:43,831 ERROR    interfaces.web       Exception on /dashboard/profitability [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/OctoBot/interfaces/web/controllers/dashboard.py", line 56, in profitability
    market_average_profitability = get_global_profitability()
  File "/home/pi/OctoBot/interfaces/trading_util.py", line 237, in get_global_profitability
    get_bot().run_in_main_asyncio_loop(trade_manager.get_profitability(with_market=True))
  File "/home/pi/OctoBot/core/octobot.py", line 78, in run_in_main_asyncio_loop
    return self.task_manager.run_in_main_asyncio_loop(coroutine)
  File "/home/pi/OctoBot/core/task_manager.py", line 148, in run_in_main_asyncio_loop
    return run_coroutine_in_asyncio_loop(coroutine, self.async_loop)
  File "/home/pi/OctoBot/tools/asyncio_tools.py", line 36, in run_coroutine_in_asyncio_loop
    raise e
  File "/home/pi/OctoBot/tools/asyncio_tools.py", line 30, in run_coroutine_in_asyncio_loop
    return future.result(DEFAULT_FUTURE_TIMEOUT)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 434, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
 2020-08-27 05:16:43,834 ERROR    TradesManager[bitfinex]
 2020-08-27 05:16:43,849 ERROR    TradesManager[bitfinex]
Traceback (most recent call last):
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 128, in get_profitability
    await self.update_portfolio_and_currencies_current_value()
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 202, in update_portfolio_and_currencies_current_value
    self.portfolio_current_value = await self.update_portfolio_current_value(current_portfolio)
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 268, in update_portfolio_current_value
    self.current_crypto_currencies_values = await self._evaluate_config_crypto_currencies_values()
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 311, in _evaluate_config_crypto_currencies_values
    values_dict[currency] = await self.evaluate_value(currency, 1)
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 342, in evaluate_value
    return await self._try_get_value_of_currency(currency, quantity)
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 283, in _try_get_value_of_currency
    if await self._update_currencies_prices(symbol):
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 111, in _update_currencies_prices
    ticker = await self.exchange.get_price_ticker(symbol)
  File "/home/pi/OctoBot/trading/exchanges/exchange_dispatcher.py", line 192, in get_price_ticker
    await self.exchange.get_price_ticker(symbol=symbol)
  File "/home/pi/OctoBot/trading/exchanges/rest_exchanges/rest_exchange.py", line 160, in get_price_ticker
    self.get_symbol_data(symbol).update_symbol_ticker(await self.client.fetch_ticker(symbol))
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/bitfinex.py", line 607, in fetch_ticker
    ticker = await self.publicGetPubtickerSymbol(self.extend(request, params))
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 113, in fetch2
    await self.throttle()
concurrent.futures._base.CancelledError


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


 2020-08-27 05:16:46,421 ERROR    TradesManager[bitfinex]
 2020-08-27 05:16:46,422 ERROR    TradesManager[bitfinex]
Traceback (most recent call last):
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 128, in get_profitability
    await self.update_portfolio_and_currencies_current_value()
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 202, in update_portfolio_and_currencies_current_value
    self.portfolio_current_value = await self.update_portfolio_current_value(current_portfolio)
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 268, in update_portfolio_current_value
    self.current_crypto_currencies_values = await self._evaluate_config_crypto_currencies_values()
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 314, in _evaluate_config_crypto_currencies_values
    values_dict[market] = await self.evaluate_value(market, 1)
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 342, in evaluate_value
    return await self._try_get_value_of_currency(currency, quantity)
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 287, in _try_get_value_of_currency
    if await self._update_currencies_prices(symbol_inverted):
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 111, in _update_currencies_prices
    ticker = await self.exchange.get_price_ticker(symbol)
  File "/home/pi/OctoBot/trading/exchanges/exchange_dispatcher.py", line 192, in get_price_ticker
    await self.exchange.get_price_ticker(symbol=symbol)
  File "/home/pi/OctoBot/trading/exchanges/rest_exchanges/rest_exchange.py", line 160, in get_price_ticker
    self.get_symbol_data(symbol).update_symbol_ticker(await self.client.fetch_ticker(symbol))
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/bitfinex.py", line 607, in fetch_ticker
    ticker = await self.publicGetPubtickerSymbol(self.extend(request, params))
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 113, in fetch2
    await self.throttle()
concurrent.futures._base.CancelledError
 2020-08-27 05:16:46,426 ERROR    TradesManager[bitfinex]
 2020-08-27 05:16:46,427 ERROR    TradesManager[bitfinex]
Traceback (most recent call last):
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 128, in get_profitability
    await self.update_portfolio_and_currencies_current_value()
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 202, in update_portfolio_and_currencies_current_value
    self.portfolio_current_value = await self.update_portfolio_current_value(current_portfolio)
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 268, in update_portfolio_current_value
    self.current_crypto_currencies_values = await self._evaluate_config_crypto_currencies_values()
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 314, in _evaluate_config_crypto_currencies_values
    values_dict[market] = await self.evaluate_value(market, 1)
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 342, in evaluate_value
    return await self._try_get_value_of_currency(currency, quantity)
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 287, in _try_get_value_of_currency
    if await self._update_currencies_prices(symbol_inverted):
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 111, in _update_currencies_prices
    ticker = await self.exchange.get_price_ticker(symbol)
  File "/home/pi/OctoBot/trading/exchanges/exchange_dispatcher.py", line 192, in get_price_ticker
    await self.exchange.get_price_ticker(symbol=symbol)
  File "/home/pi/OctoBot/trading/exchanges/rest_exchanges/rest_exchange.py", line 160, in get_price_ticker
    self.get_symbol_data(symbol).update_symbol_ticker(await self.client.fetch_ticker(symbol))
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/bitfinex.py", line 607, in fetch_ticker
    ticker = await self.publicGetPubtickerSymbol(self.extend(request, params))
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 113, in fetch2
    await self.throttle()
concurrent.futures._base.CancelledError
>

**Comment by Sascha321** [comment]
And finally the following question, does this error message have a negative effect on the way the OctoBot works? or is that just a hint?

> 
 2020-08-27 05:22:08,734 ERROR    ExchangeManager      binance is not supporting the BTC/USD trading pair.
 2020-08-27 05:22:08,735 ERROR    ExchangeManager      binance is not supporting the ETH/USD trading pair.


 2020-08-27 05:22:12,057 ERROR    ExchangeManager      bitfinex is not supporting the IOTA/USDT trading pair.


 2020-08-27 05:22:13,887 ERROR    ExchangeManager      coinbasepro is not supporting the BTC/USDT trading pair.
 2020-08-27 05:22:13,888 ERROR    ExchangeManager      coinbasepro is not supporting the ETH/USDT trading pair.
 2020-08-27 05:22:13,889 ERROR    ExchangeManager      coinbasepro is not supporting the IOTA/BTC trading pair.
 2020-08-27 05:22:13,890 ERROR    ExchangeManager      coinbasepro is not supporting the IOTA/ETH trading pair.
 2020-08-27 05:22:13,890 ERROR    ExchangeManager      coinbasepro is not supporting the IOTA/USDT trading pair.
 2020-08-27 05:22:13,892 ERROR    ExchangeManager      coinbasepro is not supporting any IOTA trading pair from current configuration.
> 

### Thank you for your help

**Comment by GuillaumeDSM** [comment]
> Hello
> 
> Most of my trades or pairings are canceled. Is this due to the attitudes or the fluctuations in the rate of the crypto currency?
> 
> > 
> 
> octo-bot08121971, [27.08.20 00:15]
> [Real Trader] Order(s) creation
> 
> * BUY_LIMIT: 0.12653 ETH at 381.59 USDT  binance 08-27 00:15
> 
> octo-bot08121971, [27.08.20 02:55]
> [Real Trader] Order(s) canceled :
> 
> * BUY_LIMIT: 0.12634 ETH at 382.14 USDT  binance 08-26 23:50
> 
> octo-bot08121971, [27.08.20 02:55]
> [Real Trader] Order(s) canceled :
> 
> * BUY_LIMIT: 0.12653 ETH at 381.59 USDT  binance 08-27 00:15
> 
> octo-bot08121971, [27.08.20 02:55]
> [Real Trader] Order(s) creation
> 
> * BUY_LIMIT: 0.12629 ETH at 382.25 USDT  binance 08-27 02:55
> 
> octo-bot08121971, [27.08.20 03:10]
> [Real Trader] Order(s) canceled :
> 
> * BUY_LIMIT: 0.12629 ETH at 382.25 USDT  binance 08-27 02:55
> 
> octo-bot08121971, [27.08.20 03:10]
> [Real Trader] Order(s) creation
> 
> * BUY_LIMIT: 0.12654 ETH at 381.68 USDT  binance 08-27 03:10
> 
> octo-bot08121971, [27.08.20 04:00]
> [Real Trader] Order(s) creation
> 
> * STOP_LOSS: 0.11750232 ETH at 0.03267 BTC  coinbasepro 08-27 04:00
> * SELL_LIMIT: 0.11750232 ETH at 0.03429 BTC  coinbasepro 08-27 04:00
> 
> octo-bot08121971, [27.08.20 04:20]
> [Real Trader] Order(s) canceled :
> 
> * STOP_LOSS: 0.11750232 ETH at 0.03267 BTC  coinbasepro 08-27 04:00
> * SELL_LIMIT: 0.11750232 ETH at 0.03429 BTC  coinbasepro 08-27 04:00
> 
> octo-bot08121971, [27.08.20 05:25]
> [Real Trader] Order(s) canceled :
> 
> * BUY_LIMIT: 0.12654 ETH at 381.68 USDT  binance 08-27 03:10
> 
> octo-bot08121971, [27.08.20 05:28]
> [Real Trader] Order(s) canceled :
> 
> * BUY_LIMIT: 0.1275 ETH at 378.79 USDT  binance 08-27 05:25
> 
> >

Hello @Sascha321,
Yes, when using the daily trading mode, if a state goes from long to short (or the opposite), existing unfilled orders are cancelled because they are not relevant anymore.

**Comment by GuillaumeDSM** [comment]
> I keep getting the following error messages
> 
> > 
> 
> 2020-08-27 05:16:43,827 ERROR asyncio_tools <coroutine object TradesManager.get_profitability at 0x6c46b030> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: None)
> 2020-08-27 05:16:43,831 ERROR interfaces.web Exception on /dashboard/profitability [GET]
> Traceback (most recent call last):
> File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
> response = self.full_dispatch_request()
> File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "/home/pi/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
> raise value
> File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
> rv = self.dispatch_request()
> File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "/home/pi/OctoBot/interfaces/web/controllers/dashboard.py", line 56, in profitability
> market_average_profitability = get_global_profitability()
> File "/home/pi/OctoBot/interfaces/trading_util.py", line 237, in get_global_profitability
> get_bot().run_in_main_asyncio_loop(trade_manager.get_profitability(with_market=True))
> File "/home/pi/OctoBot/core/octobot.py", line 78, in run_in_main_asyncio_loop
> return self.task_manager.run_in_main_asyncio_loop(coroutine)
> File "/home/pi/OctoBot/core/task_manager.py", line 148, in run_in_main_asyncio_loop
> return run_coroutine_in_asyncio_loop(coroutine, self.async_loop)
> File "/home/pi/OctoBot/tools/asyncio_tools.py", line 36, in run_coroutine_in_asyncio_loop
> raise e
> File "/home/pi/OctoBot/tools/asyncio_tools.py", line 30, in run_coroutine_in_asyncio_loop
> return future.result(DEFAULT_FUTURE_TIMEOUT)
> File "/usr/lib/python3.7/concurrent/futures/_base.py", line 434, in result
> raise TimeoutError()
> concurrent.futures._base.TimeoutError
> 2020-08-27 05:16:43,834 ERROR TradesManager[bitfinex]
> 2020-08-27 05:16:43,849 ERROR TradesManager[bitfinex]
> Traceback (most recent call last):
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 128, in get_profitability
> await self.update_portfolio_and_currencies_current_value()
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 202, in update_portfolio_and_currencies_current_value
> self.portfolio_current_value = await self.update_portfolio_current_value(current_portfolio)
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 268, in update_portfolio_current_value
> self.current_crypto_currencies_values = await self._evaluate_config_crypto_currencies_values()
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 311, in _evaluate_config_crypto_currencies_values
> values_dict[currency] = await self.evaluate_value(currency, 1)
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 342, in evaluate_value
> return await self._try_get_value_of_currency(currency, quantity)
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 283, in _try_get_value_of_currency
> if await self._update_currencies_prices(symbol):
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 111, in _update_currencies_prices
> ticker = await self.exchange.get_price_ticker(symbol)
> File "/home/pi/OctoBot/trading/exchanges/exchange_dispatcher.py", line 192, in get_price_ticker
> await self.exchange.get_price_ticker(symbol=symbol)
> File "/home/pi/OctoBot/trading/exchanges/rest_exchanges/rest_exchange.py", line 160, in get_price_ticker
> self.get_symbol_data(symbol).update_symbol_ticker(await self.client.fetch_ticker(symbol))
> File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/bitfinex.py", line 607, in fetch_ticker
> ticker = await self.publicGetPubtickerSymbol(self.extend(request, params))
> File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 113, in fetch2
> await self.throttle()
> concurrent.futures._base.CancelledError
> 
> 2020-08-27 05:16:46,421 ERROR TradesManager[bitfinex]
> 2020-08-27 05:16:46,422 ERROR TradesManager[bitfinex]
> Traceback (most recent call last):
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 128, in get_profitability
> await self.update_portfolio_and_currencies_current_value()
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 202, in update_portfolio_and_currencies_current_value
> self.portfolio_current_value = await self.update_portfolio_current_value(current_portfolio)
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 268, in update_portfolio_current_value
> self.current_crypto_currencies_values = await self._evaluate_config_crypto_currencies_values()
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 314, in _evaluate_config_crypto_currencies_values
> values_dict[market] = await self.evaluate_value(market, 1)
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 342, in evaluate_value
> return await self._try_get_value_of_currency(currency, quantity)
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 287, in _try_get_value_of_currency
> if await self._update_currencies_prices(symbol_inverted):
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 111, in _update_currencies_prices
> ticker = await self.exchange.get_price_ticker(symbol)
> File "/home/pi/OctoBot/trading/exchanges/exchange_dispatcher.py", line 192, in get_price_ticker
> await self.exchange.get_price_ticker(symbol=symbol)
> File "/home/pi/OctoBot/trading/exchanges/rest_exchanges/rest_exchange.py", line 160, in get_price_ticker
> self.get_symbol_data(symbol).update_symbol_ticker(await self.client.fetch_ticker(symbol))
> File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/bitfinex.py", line 607, in fetch_ticker
> ticker = await self.publicGetPubtickerSymbol(self.extend(request, params))
> File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 113, in fetch2
> await self.throttle()
> concurrent.futures._base.CancelledError
> 2020-08-27 05:16:46,426 ERROR TradesManager[bitfinex]
> 2020-08-27 05:16:46,427 ERROR TradesManager[bitfinex]
> Traceback (most recent call last):
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 128, in get_profitability
> await self.update_portfolio_and_currencies_current_value()
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 202, in update_portfolio_and_currencies_current_value
> self.portfolio_current_value = await self.update_portfolio_current_value(current_portfolio)
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 268, in update_portfolio_current_value
> self.current_crypto_currencies_values = await self._evaluate_config_crypto_currencies_values()
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 314, in _evaluate_config_crypto_currencies_values
> values_dict[market] = await self.evaluate_value(market, 1)
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 342, in evaluate_value
> return await self._try_get_value_of_currency(currency, quantity)
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 287, in _try_get_value_of_currency
> if await self._update_currencies_prices(symbol_inverted):
> File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 111, in _update_currencies_prices
> ticker = await self.exchange.get_price_ticker(symbol)
> File "/home/pi/OctoBot/trading/exchanges/exchange_dispatcher.py", line 192, in get_price_ticker
> await self.exchange.get_price_ticker(symbol=symbol)
> File "/home/pi/OctoBot/trading/exchanges/rest_exchanges/rest_exchange.py", line 160, in get_price_ticker
> self.get_symbol_data(symbol).update_symbol_ticker(await self.client.fetch_ticker(symbol))
> File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/bitfinex.py", line 607, in fetch_ticker
> ticker = await self.publicGetPubtickerSymbol(self.extend(request, params))
> File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 113, in fetch2
> await self.throttle()
> concurrent.futures._base.CancelledError
> 
> >

This happens sometimes with 0.3 when there is too many things to update and the exchange is not replying fast enough, it's just a display issue and will not affect your bot's behavior

**Comment by GuillaumeDSM** [comment]
> the following question, does this error message have a negative effect

This is a hint to inform you that these exchanges are not allowing trading on these pairs, it will not have any effect on your bot (except that it will not trade these pairs on these exchanges, obviously)
