### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Sascha321** [Drakkar-Software/OctoBot#1301]
Can it be that I don't get a trade because of this message?

OctoBot 0.39
Rasbian

 2020-08-28 14:37:15,338 ERROR    asyncio_tools        <coroutine object TradesManager.get_profitabilit                                                                  y at 0x6ceb46f0> coroutine took too long to execute, cancelling the task. (current task before starting                                                                   this one: None, actual current task before cancel: None)
 2020-08-28 14:37:15,340 ERROR    interfaces.web       Exception on /dashboard/profitability [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/OctoBot/interfaces/web/controllers/dashboard.py", line 56, in profitability
    market_average_profitability = get_global_profitability()
  File "/home/pi/OctoBot/interfaces/trading_util.py", line 237, in get_global_profitability
    get_bot().run_in_main_asyncio_loop(trade_manager.get_profitability(with_market=True))
  File "/home/pi/OctoBot/core/octobot.py", line 78, in run_in_main_asyncio_loop
    return self.task_manager.run_in_main_asyncio_loop(coroutine)
  File "/home/pi/OctoBot/core/task_manager.py", line 148, in run_in_main_asyncio_loop
    return run_coroutine_in_asyncio_loop(coroutine, self.async_loop)
  File "/home/pi/OctoBot/tools/asyncio_tools.py", line 36, in run_coroutine_in_asyncio_loop
    raise e
  File "/home/pi/OctoBot/tools/asyncio_tools.py", line 30, in run_coroutine_in_asyncio_loop
    return future.result(DEFAULT_FUTURE_TIMEOUT)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 434, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
 2020-08-28 14:37:15,342 ERROR    TradesManager[bitfinex]
 2020-08-28 14:37:15,355 ERROR    TradesManager[bitfinex]
Traceback (most recent call last):
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 128, in get_profitability
    await self.update_portfolio_and_currencies_current_value()
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 202, in update_portfolio_and_currencie                                                                  s_current_value
    self.portfolio_current_value = await self.update_portfolio_current_value(current_portfolio)
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 268, in update_portfolio_current_value
    self.current_crypto_currencies_values = await self._evaluate_config_crypto_currencies_values()
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 311, in _evaluate_config_crypto_curren                                                                  cies_values
    values_dict[currency] = await self.evaluate_value(currency, 1)
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 342, in evaluate_value
    return await self._try_get_value_of_currency(currency, quantity)
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 283, in _try_get_value_of_currency
    if await self._update_currencies_prices(symbol):
  File "/home/pi/OctoBot/trading/trader/trades_manager.py", line 111, in _update_currencies_prices
    ticker = await self.exchange.get_price_ticker(symbol)
  File "/home/pi/OctoBot/trading/exchanges/exchange_dispatcher.py", line 192, in get_price_ticker
    await self.exchange.get_price_ticker(symbol=symbol)
  File "/home/pi/OctoBot/trading/exchanges/rest_exchanges/rest_exchange.py", line 160, in get_price_tic                                                                  ker
    self.get_symbol_data(symbol).update_symbol_ticker(await self.client.fetch_ticker(symbol))
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/bitfinex.py", line 607, in fetch                                                                  _ticker
    ticker = await self.publicGetPubtickerSymbol(self.extend(request, params))
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 113, in                                                                   fetch2
    await self.throttle()
concurrent.futures._base.CancelledError

**Comment by Herklos** [comment]
Hi @Sascha321, it's a well known bug of Octobot 0.3.9 that shouldn't impact Octobot trading behavior. It's only impacting web interface. We didn't fix the bug yet, we (@GuillaumeDSM and me) were focused on OctoBot's next big version (aka v0.4.0).

**Comment by Sascha321** [comment]
Wouldn't it be better to first eliminate all errors in version 0.39 and then, if version 0.39 runs without errors, do a new update? So you always drag errors that have not been recognized, see Microsoft.

**Comment by Sascha321** [comment]
> 

 2020-08-29 08:58:41,326 ERROR    OctoBot Launcher     OctoBot Exception : bitfinex {"error":"ERR_RATE_LIMIT"}
Traceback (most recent call last):
  File "/home/pi/OctoBot/tools/commands.py", line 110, in start_bot
    await bot.initialize()
  File "/home/pi/OctoBot/core/octobot.py", line 68, in initialize
    await self.exchange_factory.create()
  File "/home/pi/OctoBot/core/exchange_factory.py", line 58, in create
    await self._create_exchange_traders(exchange_class_string)
  File "/home/pi/OctoBot/core/exchange_factory.py", line 79, in _create_exchange_traders
    await exchange_manager.initialize()
  File "/home/pi/OctoBot/tools/initializable.py", line 28, in initialize
    await self.initialize_impl()
  File "/home/pi/OctoBot/trading/exchanges/exchange_manager.py", line 63, in initialize_impl
    await self.create_exchanges()
  File "/home/pi/OctoBot/trading/exchanges/exchange_manager.py", line 86, in create_exchanges
    await self.exchange.initialize()
  File "/home/pi/OctoBot/tools/initializable.py", line 28, in initialize
    await self.initialize_impl()
  File "/home/pi/OctoBot/trading/exchanges/rest_exchanges/rest_exchange.py", line 59, in initialize_impl
    await self.client.load_markets()
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 187, in load_markets
    markets = await self.fetch_markets(params)
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/bitfinex.py", line 485, in fetch_markets
    ids = await self.publicGetSymbols()
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 116, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 169, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/bitfinex.py", line 1097, in handle_errors
    raise exact[message](feedback)
ccxt.base.errors.DDoSProtection: bitfinex {"error":"ERR_RATE_LIMIT"}
 2020-08-29 08:58:41,348 ERROR    root                   File "start.py", line 295, in <module>
    main()
  File "start.py", line 291, in main
    start_octobot(args)
  File "start.py", line 199, in start_octobot
    asyncio.run(Commands.start_bot(bot, logger), debug=debug_mode)
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/OctoBot/tools/commands.py", line 122, in start_bot
    raise e
  File "/home/pi/OctoBot/tools/commands.py", line 110, in start_bot
    await bot.initialize()
  File "/home/pi/OctoBot/core/octobot.py", line 68, in initialize
    await self.exchange_factory.create()
  File "/home/pi/OctoBot/core/exchange_factory.py", line 58, in create
    await self._create_exchange_traders(exchange_class_string)
  File "/home/pi/OctoBot/core/exchange_factory.py", line 79, in _create_exchange_traders
    await exchange_manager.initialize()
  File "/home/pi/OctoBot/tools/initializable.py", line 28, in initialize
    await self.initialize_impl()
  File "/home/pi/OctoBot/trading/exchanges/exchange_manager.py", line 63, in initialize_impl
    await self.create_exchanges()
  File "/home/pi/OctoBot/trading/exchanges/exchange_manager.py", line 86, in create_exchanges
    await self.exchange.initialize()
  File "/home/pi/OctoBot/tools/initializable.py", line 28, in initialize
    await self.initialize_impl()
  File "/home/pi/OctoBot/trading/exchanges/rest_exchanges/rest_exchange.py", line 59, in initialize_impl
    await self.client.load_markets()
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 187, in load_markets
    markets = await self.fetch_markets(params)
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/bitfinex.py", line 485, in fetch_markets
    ids = await self.publicGetSymbols()
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 116, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 169, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/pi/.local/lib/python3.7/site-packages/ccxt/async_support/bitfinex.py", line 1097, in handle_errors
    raise exact[message](feedback)
NoneType: None
 2020-08-29 08:58:41,359 ERROR    root                 <class 'ccxt.base.errors.DDoSProtection'>: bitfinex {"error":"ERR_RATE_LIMIT"}
NoneType: None

>

**Comment by Herklos** [comment]
@Sascha321 ERR_RATE_LIMIT errors are not related to OctoBot but the library we use to connect to exchanges. You should prefer using bitfinex2 instead of bitfinex and update the ccxt library dependening on your installation method.

**Comment by Sascha321** [comment]
@Herklos, i need to provide ccxt.bitfinex{'enableRateLimit': True}

**Comment by Herklos** [comment]
@Sascha321 Yes it's the fix that I would have proposed to you if test of bitfinex2 didn't fix the error rate limit issue.

**Comment by Sascha321** [comment]
Octobot doesn't start with Bitfinex2, I have to delete Bitfinex2 in "config.json" so that Octobot starts again. I think there is a big bug in the Octobot
