### ISSUE TITLE
Can't rename backtesting historical data

### ISSUE THREAD

**Issue by valouvaliavlo** [Drakkar-Software/OctoBot#1514]
If historical data have been renamed this will throw an error in log. In web interface it's marked at started

logs : 
`Traceback (most recent call last):
  File "Octobot\octobot\backtesting\independent_backtesting.py", line 69, in initialize_and_run
    await self.octobot_backtesting.initialize_and_run()
  File "Octobot\octobot\backtesting\octobot_backtesting.py", line 61, in initialize_and_run
    await self._init_exchanges()
  File "Octobot\octobot\backtesting\octobot_backtesting.py", line 200, in _init_exchanges
    await backtesting_api.adapt_backtesting_channels(self.backtesting,
  File "D:\Users\cosse\Desktop\OctoBot\Octobot-Backtesting\octobot_backtesting\api\backtesting.py", line 65, in adapt_backtesting_channels
    min_timestamp = max(min_timestamps) if run_on_common_part_only else min(min_timestamps)
ValueError: max() arg is an empty sequence
2021-02-02 20:19:28 ERROR  IndependentBacktesting logging_util.py:172      Error when running backtesting: max() arg is an empty sequence (ValueError)`

**Comment by GuillaumeDSM** [comment]
For now the name is important therefore if you change it your data file will not work anymore. However it should not crash, we will fix this :)
