### ISSUE TITLE
[Trading][Open Order][CoinbasePro] Invalid parameter range - limit

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot#1531]
Phisher on discord channel : 

> i keep getting the error: "AsyncJob-_open_orders_fetch_and_push coinbasepro Invalid parameter range - limit" any idea on how to fix it? this is on the newest version

https://discord.com/channels/530629985661222912/530636611222765593/808900776994930699

The new version is 0.4.0-beta3.

It seems to be an issue with order fetching on coinbase. The default limit for coinbasepro is 100, we are asking for 200 in OrdersUpdater.

**Comment by camfisher** [comment]
This will probably help also:

2021-02-09 22:19:18,630 ERROR    AsyncJob-_open_orders_fetch_and_push coinbasepro Invalid parameter range - limit
Traceback (most recent call last):
  File "octobot_commons\async_job.py", line 193, in octobot_commons.async_job.AsyncJob._run
  File "octobot_trading\personal_data\orders\channel\orders_updater.py", line 93, in _open_orders_fetch_and_push
  File "octobot_trading\exchanges\implementations\spot_ccxt_exchange.py", line 150, in get_open_orders
  File "octobot_trading\exchanges\connectors\ccxt_exchange.py", line 263, in get_open_orders
  File "ccxt\async_support\coinbasepro.py", line 791, in fetch_open_orders
  File "ccxt\async_support\coinbasepro.py", line 1121, in request
  File "ccxt\async_support\base\exchange.py", line 95, in fetch2
  File "ccxt\async_support\base\exchange.py", line 153, in fetch
  File "ccxt\async_support\coinbasepro.py", line 1117, in handle_errors
ccxt.base.errors.ExchangeError: coinbasepro Invalid parameter range - limit

**Comment by Herklos** [comment]
> This will probably help also:
> 
> 2021-02-09 22:19:18,630 ERROR AsyncJob-_open_orders_fetch_and_push coinbasepro Invalid parameter range - limit
> Traceback (most recent call last):
> File "octobot_commons\async_job.py", line 193, in octobot_commons.async_job.AsyncJob._run
> File "octobot_trading\personal_data\orders\channel\orders_updater.py", line 93, in _open_orders_fetch_and_push
> File "octobot_trading\exchanges\implementations\spot_ccxt_exchange.py", line 150, in get_open_orders
> File "octobot_trading\exchanges\connectors\ccxt_exchange.py", line 263, in get_open_orders
> File "ccxt\async_support\coinbasepro.py", line 791, in fetch_open_orders
> File "ccxt\async_support\coinbasepro.py", line 1121, in request
> File "ccxt\async_support\base\exchange.py", line 95, in fetch2
> File "ccxt\async_support\base\exchange.py", line 153, in fetch
> File "ccxt\async_support\coinbasepro.py", line 1117, in handle_errors
> ccxt.base.errors.ExchangeError: coinbasepro Invalid parameter range - limit

Perfect :+1: Thank you

**Comment by Herklos** [comment]
Seems to be a new maximum value for pagination on coinbasepro : https://docs.pro.coinbase.com/#pagination.

![image](https://user-images.githubusercontent.com/10454670/107571644-79ce9380-6beb-11eb-9db1-5e2e150edd1b.png)

**Comment by GuillaumeDSM** [comment]
To fix this (untill 0.4.0b4 is released): 
Use the OctoBot dev branch and latest tentacles:
https://docs.octobot.online/pages/With-Python-only.html#using-the-latest-version-dev-branch
