### ISSUE TITLE
Could not find a version that satisfies the requirement OctoBot-Commons==1.5.4

### ISSUE THREAD

**Issue by higi** [Drakkar-Software/OctoBot#1553]
Hey, having issue installing Octobot on Debain 10, Python 3.8.2

Collecting cython==0.29.21 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/6b/36/d6c18632a339dafa54fd128b0dd2c36c6dc4bc86b8e0d366ccd9f22b480a/Cython-0.29.21-cp37-cp37m-manylinux1_x86_64.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 708kB/s
Collecting OctoBot-Commons==1.5.4 (from -r requirements.txt (line 5))
  Could not find a version that satisfies the requirement OctoBot-Commons==1.5.4 (from -r requirements.txt (line 5)) (from versions: 1.0.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10, 1.3.11, 1.3.12, 1.3.13, 1.3.14, 1.3.15, 1.3.16, 1.3.17, 1.3.18, 1.3.19, 1.3.20, 1.3.21, 1.3.22, 1.3.23, 1.3.24, 1.3.25, 1.3.26, 1.3.27, 1.3.28, 1.3.29, 1.3.30, 1.3.31, 1.3.32, 1.3.33, 1.3.34, 1.3.35, 1.3.36, 1.3.37, 1.3.38, 1.3.39, 1.3.40, 1.3.41, 1.3.42, 1.3.43, 1.3.44, 1.3.45, 1.3.46, 1.4.0, 1.4.1)
No matching distribution found for OctoBot-Commons==1.5.4 (from -r requirements.txt (line 5))

**Comment by GuillaumeDSM** [comment]
Hi, what is the architecture of your computer ?

**Comment by higi** [comment]
> Hi, what is the architecture of your computer ?

Hey,

Aws amazon 1c, 1gb ram, Debian 10, Python 3.8.2

**Comment by GuillaumeDSM** [comment]
I didn't see it at first but you are downloading for python 3.7, OctoBot requires python 3.8 (see the cp37 in the Cython package name). Using the right python should fix this

**Comment by higi** [comment]
THX, now i am on:
 python3.8 -m pip install -Ur requirements.txt
Collecting cython==0.29.21 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/9f/05/959e78f2aeade1c9e85a7adc4c376f454ecaeb4cb6b079ca7a85684b69c1/Cython-0.29.21-cp38-cp38-manylinux1_x86_64.whl (1.9MB)
     |████████████████████████████████| 1.9MB 11.5MB/s
Collecting OctoBot-Commons==1.5.4 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/95/ab/47de0d0a1f7efd62c0aae2c8eebe9f2a48ef6b04bea5ab3b269106efca56/OctoBot-Commons-1.5.4.tar.gz (658kB)
     |████████████████████████████████| 665kB 17.3MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z_pf4fec/OctoBot-Commons/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z_pf4fec/OctoBot-Commons/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-z_pf4fec/OctoBot-Commons/
    Complete output (77 lines):
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-qbky88yx/cryptography-3.4.6/setup.py", line 14, in <module>
        #  You should have received a copy of the GNU Lesser General Public
    ModuleNotFoundError: No module named 'setuptools_rust'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-z_pf4fec/OctoBot-Commons/setup.py", line 68, in <module>
        setup(
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/local/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-qbky88yx/cryptography-3.4.6/setup.py", line 14, in <module>
        #  You should have received a copy of the GNU Lesser General Public
    ModuleNotFoundError: No module named 'setuptools_rust'

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by GuillaumeDSM** [comment]
```Upgrade to the latest pip and try again. This will fix errors for most
        users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
```
=> can you try to update pip ?

**Comment by higi** [comment]
Thx for helping me, got it working by upgrading pip:)

Btw is therw how to integrate it with nginx server? And adding ssl

**Comment by Herklos** [comment]
You can add nginx with an ssl certificate to your setup.  How do you want to configure it? With docker or with python sources ?

**Comment by higi** [comment]
Python sources:)

**Comment by higi** [comment]
> You can add nginx with an ssl certificate to your setup. How do you want to configure it? With docker or with python sources ?

Could u please send me working config for nginx site

**Comment by Herklos** [comment]
@higi You can find a docker-compose that generates a nginx config for OctoBot at https://github.com/Drakkar-Software/OctoBot/pull/1554.

If you don't want to use docker [here](https://github.com/Drakkar-Software/OctoBot/files/6018764/default.conf.txt) the generated conf file.

PS : there is no ssl conf for now.

**Comment by Herklos** [comment]
@higi You can find a doc about how to add ssl integration with docker-compose at #1555.

**Comment by higi** [comment]
TY, helped a lot:) 

Can be closed now. Got it working with ssl.

**Comment by Herklos** [comment]
Nice ! 👍

**Comment by Herklos** [comment]
Don't hesitate to open a new issue if you have any other question 😉
