### ISSUE TITLE
Docker image 0.4.0b8 ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by dbstraffin** [Drakkar-Software/OctoBot#1638]
## Step 1: Have you search for this issue before posting it?

Yes, nobody has reported it yet.

## Step 2: Describe your environment
  * OS : Docker
  * Python Version: 3.8
 
## Step 3: Describe the problem:
**Describe the bug**
When starting the docker container for drakkarsoftware/octobot:0.4.0b8, the web interface never appears and python stack traces for import errors appear in the logs.

**Expected behavior**
Proper startup of application.

### Steps to reproduce:

  1. Run docker image drakkarsoftware/octobot:0.4.0b8
  

### Relevant code exceptions or logs:
 
```
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
,  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
,  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
,  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
,  File "/opt/venv/lib/python3.8/site-packages/OctoBot-0.4.0b8-py3.8-linux-x86_64.egg/octobot/cli.py", line 40, in <module>
,    import octobot.octobot as octobot_class
,  File "octobot.py", line 1, in init octobot.octobot
,  File "octobot_api.py", line 17, in init octobot.octobot_api
,  File "/opt/venv/lib/python3.8/site-packages/OctoBot-0.4.0b8-py3.8-linux-x86_64.egg/octobot/commands.py", line 32, in <module>
,    import octobot.api.strategy_optimizer as strategy_optimizer_api
,  File "/opt/venv/lib/python3.8/site-packages/OctoBot-0.4.0b8-py3.8-linux-x86_64.egg/octobot/api/__init__.py", line 19, in <module>
,    from octobot.api import updater
,  File "/opt/venv/lib/python3.8/site-packages/OctoBot-0.4.0b8-py3.8-linux-x86_64.egg/octobot/api/updater.py", line 17, in <module>
,    import octobot.updater.updater_factory as updater_factory
,  File "/opt/venv/lib/python3.8/site-packages/OctoBot-0.4.0b8-py3.8-linux-x86_64.egg/octobot/updater/__init__.py", line 17, in <module>
,    from octobot.updater import updater_factory
,  File "updater_factory.py", line 20, in init octobot.updater.updater_factory
,  File "binary_updater.py", line 1, in init octobot.updater.binary_updater
,  File "updater.py", line 16, in init octobot.updater.updater
,ModuleNotFoundError: No module named 'packaging'
```

[octobot_logs.txt](https://github.com/Drakkar-Software/OctoBot/files/6285450/octobot_logs.txt)

**Comment by Herklos** [comment]
Hi @dbstraffin, thanks for reporting. The 0.4.0b8 version is not yet officially release, we have some fixes to do. You should install 0.4.0b7 if you want to use OctoBot now. The 0.4.0b8 will be available very soon.

**Comment by dbstraffin** [comment]
Yup, I rolled back to 0.4.0b7 and everything is fine.  I just wanted to make sure you knew about the issue.  Thanks again!

**Comment by Herklos** [comment]
> Yup, I rolled back to 0.4.0b7 and everything is fine. I just wanted to make sure you knew about the issue. Thanks again!

We didn't know this one, thanks for reporting !

**Comment by dbstraffin** [comment]
FYI - It looks like this same issue is present in the pypi package for octobot 0.4.0b8. 

Here I'm running out of a python 3.8 virtualenv with only `OctoBot==0.4.0b8` in requirements.txt:
```
$ make run 
.venv/bin/OctoBot
Traceback (most recent call last):
  File ".venv/bin/OctoBot", line 5, in <module>
    from octobot.cli import main
  File "/home/dstraffin/src/octobot/.venv/lib/python3.8/site-packages/octobot/cli.py", line 40, in <module>
    import octobot.octobot as octobot_class
  File "octobot/octobot.py", line 1, in init octobot.octobot
  File "octobot/octobot_api.py", line 17, in init octobot.octobot_api
  File "/home/dstraffin/src/octobot/.venv/lib/python3.8/site-packages/octobot/commands.py", line 32, in <module>
    import octobot.api.strategy_optimizer as strategy_optimizer_api
  File "/home/dstraffin/src/octobot/.venv/lib/python3.8/site-packages/octobot/api/__init__.py", line 19, in <module>
    from octobot.api import updater
  File "/home/dstraffin/src/octobot/.venv/lib/python3.8/site-packages/octobot/api/updater.py", line 17, in <module>
    import octobot.updater.updater_factory as updater_factory
  File "/home/dstraffin/src/octobot/.venv/lib/python3.8/site-packages/octobot/updater/__init__.py", line 17, in <module>
    from octobot.updater import updater_factory
  File "octobot/updater/updater_factory.py", line 20, in init octobot.updater.updater_factory
  File "octobot/updater/binary_updater.py", line 1, in init octobot.updater.binary_updater
  File "octobot/updater/updater.py", line 16, in init octobot.updater.updater
ModuleNotFoundError: No module named 'packaging'
Makefile:19: recipe for target 'run' failed
make: *** [run] Error 1
$ cat requirements.txt 
OctoBot==0.4.0b8

```

**Comment by dbstraffin** [comment]
Its easy to workaround by adding `packaging` to requirements.txt

**Comment by Herklos** [comment]
HI @dbstraffin, thanks, we already fixed it but we can't reupload on pypi, it will be available in the next version.
