### ISSUE TITLE
BTCTURK exchange not working any more

### ISSUE THREAD

**Issue by mertdogan** [Drakkar-Software/OctoBot#1666]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/Drakkar-Software/OctoBot/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment
  * Windows EXE release
  * Python Version: 3.8
  * In case you are not using a binary version:
    * Branch: Master
    * Last Commit ID: _____ (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
**Describe the bug**
When select btcturk from exchange list error occures at console:
WebConfigurationModel btcturk GET https://www.btcturk.com/api/ticker 405 Not Allowed Method not supported anymore. Please refer to https://docs.btcturk.com

**Expected behavior**

### Steps to reproduce:

  1. Select BTCTURK and add from exchange list.
  2. Restart
  3. Error occures at OctoBot_windows_x64.exe console.
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:
 
```
 2021-04-27 00:25:07,069 ERROR    OctoBotChannelTradingConsumer Error when initializing trading mode, btcturk exchange connection is closed to increase performances: As non symbol-wildcard trading mode, DailyTradingMode requires at least one exchange trading pair to be initialized. None of the required pairs are available on btcturk.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000273A4C56040>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 719, in call_soon
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000273A4C56040>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 719, in call_soon
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
 2021-04-27 00:27:29,716 ERROR    WebConfigurationModel btcturk GET https://www.btcturk.com/api/ticker 405 Not Allowed Method not supported anymore. Please refer to https://docs.btcturk.com
Traceback (most recent call last):
  File "ccxt\base\exchange.py", line 602, in fetch
  File "requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 405 Client Error: Not Allowed for url: https://www.btcturk.com/api/ticker

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Yüklenenler\tentacles\Services\Interfaces\web_interface\models\configuration.py", line 521, in get_symbol_list
    inst.load_markets()
  File "ccxt\base\exchange.py", line 1374, in load_markets
  File "ccxt\btcturk.py", line 71, in fetch_markets
  File "ccxt\base\exchange.py", line 470, in inner
  File "ccxt\base\exchange.py", line 495, in request
  File "ccxt\base\exchange.py", line 491, in fetch2
  File "ccxt\base\exchange.py", line 619, in fetch
  File "ccxt\base\exchange.py", line 655, in handle_http_status_code
ccxt.base.errors.ExchangeNotAvailable: btcturk GET https://www.btcturk.com/api/ticker 405 Not Allowed Method not supported anymore. Please refer to https://docs.btcturk.com
 2021-04-27 00:27:29,745 ERROR    WebConfigurationModel error when loading symbol list for btcturk: btcturk GET https://www.btcturk.com/api/ticker 405 Not Allowed Method not supported anymore. Please refer to https://docs.btcturk.com (ExchangeNotAvailable)
```

**Comment by Herklos** [comment]
Hi @mertdogan, this error is not related to OctoBot, please open an issue on https://github.com/ccxt/ccxt.

**Comment by mertdogan** [comment]
> Hi @mertdogan, this error is not related to OctoBot, please open an issue on https://github.com/ccxt/ccxt.
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/91253698/ea8e3c00-171a-11ea-9a81-e79b426fe455"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[ccxt/ccxt](https://github.com/ccxt/ccxt)**A JavaScript / Python / PHP cryptocurrency trading API with support for more than 120 bitcoin/altcoin exchanges - ccxt/ccxt

Thank you. Is there a way to edit related files myself?

**Comment by kroitor** [comment]
@Herklos please, upgrade the CCXT version to the most recent one, we have pushed a number of fixes for BTCTurk v2 recently. Thank you!

**Comment by mertdogan** [comment]
Developer of CCTX replied as below. I don't know how can i upgrade your integrated cctx version :/ 

@mertdogan please upgrade your version of CCXT to the most recent one.

pip3 install -U ccxt
If you are installing a precompiled binary from a 3rd-party developer, then, please, ask the developer of your bot to upgrade CCXT and provide a fresh build of the executable. Let us know if that does not answer your question.

**Comment by mertdogan** [comment]
I'm using windows x64 exe version.
