### ISSUE TITLE
Unable to install by manuel python installation process

### ISSUE THREAD

**Issue by mertdogan** [Drakkar-Software/OctoBot#1667]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/Drakkar-Software/OctoBot/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment
  * OS : Windows
  * Python Version: Python 3.9.4
  * In case you are not using a binary version:
    * Branch: Master
    * Last Commit ID: 8dccccde84e674dea477ac3640d9264275fe1400
 
## Step 3: Describe the problem:
**Describe the bug**
I tried to install OctoBot by manuel commands below:

git clone https://github.com/Drakkar-Software/OctoBot.git
cd OctoBot
python -m pip install -Ur requirements.txt
python start.py

And error messages occured and can't installation failed.

**Expected behavior**
Only run command but failed.

### Steps to reproduce:

  1. Run commands above.
  2. Error occures at 
python -m pip install -Ur requirements.txt
step.
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:
![image](https://user-images.githubusercontent.com/1324617/116167778-adf52300-a709-11eb-83ae-17382b7a0001.png)

 
```
D:\OctoBot>python -m pip install -Ur requirements.txt
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: C:\Python\Python39\Include\UNKNOWN
sysconfig: C:\Python\Python39\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Collecting cython==0.29.22
  Using cached Cython-0.29.22-py2.py3-none-any.whl (980 kB)
Collecting OctoBot-Commons==1.5.19
  Using cached OctoBot_Commons-1.5.19-cp39-cp39-win_amd64.whl
Collecting OctoBot-Trading==1.12.5
  Using cached OctoBot-Trading-1.12.5.tar.gz (9.2 MB)
Collecting OctoBot-Evaluators==1.6.15
  Using cached OctoBot-Evaluators-1.6.15.tar.gz (600 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python\Python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\temp\\pip-install-0fpha6m8\\octobot-evaluators_64d534bc5dfa44bf8feaae6efcc6165b\\setup.py'"'"'; __file__='"'"'C:\\temp\\pip-install-0fpha6m8\\octobot-evaluators_64d534bc5dfa44bf8feaae6efcc6165b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\temp\pip-pip-egg-info-t5hwfz2c'
         cwd: C:\temp\pip-install-0fpha6m8\octobot-evaluators_64d534bc5dfa44bf8feaae6efcc6165b\
    Complete output (66 lines):
      ERROR: Command errored out with exit status 1:
       command: 'C:\Python\Python39\python.exe' 'C:\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\temp\tmpuxzh6mez'
           cwd: C:\temp\pip-wheel-3g3b5nxz\tulipy_e59ce80018714f7f9ea2adf4e3ae0213
      Complete output (29 lines):
      C:\temp\pip-build-env-l1qn38p8\overlay\Lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      creating build\lib.win-amd64-3.9\tulipy
      copying tulipy\__init__.py -> build\lib.win-amd64-3.9\tulipy
      running build_ext
      skipping 'tulipy/lib\__init__.c' Cython extension (up-to-date)
      building 'tulipy.lib' extension
      creating build\temp.win-amd64-3.9
      creating build\temp.win-amd64-3.9\Release
      creating build\temp.win-amd64-3.9\Release\libindicators
      creating build\temp.win-amd64-3.9\Release\tulipy
      creating build\temp.win-amd64-3.9\Release\tulipy\lib
      C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ilibindicators -Itulipy/lib -IC:\temp\pip-build-env-l1qn38p8\overlay\Lib\site-packages\numpy\core\include -IC:\Python\Python39\include -IC:\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt /Tclibindicators/tiamalgamation.c /Fobuild\temp.win-amd64-3.9\Release\libindicators/tiamalgamation.obj
      tiamalgamation.c
      C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ilibindicators -Itulipy/lib -IC:\temp\pip-build-env-l1qn38p8\overlay\Lib\site-packages\numpy\core\include -IC:\Python\Python39\include -IC:\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt /Tctulipy/lib\__init__.c /Fobuild\temp.win-amd64-3.9\Release\tulipy/lib\__init__.obj
      __init__.c
      c:\temp\pip-build-env-l1qn38p8\overlay\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
      tulipy/lib\__init__.c(8102): error C2039: 'tp_print': bir '_typeobject' \x81yesi de§il
      c:\python\python39\include\cpython/object.h(193): note: '_typeobject' bildirimine bak\x8dn
      tulipy/lib\__init__.c(10033): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      c:\python\python39\include\cpython/unicodeobject.h(446): note: '_PyUnicode_get_wstr_length' bildirimine bak\x8dn
      tulipy/lib\__init__.c(10049): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      c:\python\python39\include\cpython/unicodeobject.h(446): note: '_PyUnicode_get_wstr_length' bildirimine bak\x8dn
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      ----------------------------------------
      ERROR: Failed building wheel for tulipy
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "C:\Python\Python39\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "C:\Python\Python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Python\\Python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\temp\\tmp7izu39a_', '--quiet', 'tulipy==0.4.0']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\temp\pip-install-0fpha6m8\octobot-evaluators_64d534bc5dfa44bf8feaae6efcc6165b\setup.py", line 70, in <module>
        setup(
      File "C:\Python\Python39\lib\site-packages\setuptools\__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "C:\Python\Python39\lib\site-packages\setuptools\__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\Python\Python39\lib\site-packages\setuptools\dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "C:\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "C:\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "C:\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 1076, in obtain
        return installer(requirement)
      File "C:\Python\Python39\lib\site-packages\setuptools\dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "C:\Python\Python39\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['C:\\Python\\Python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\temp\\tmp7izu39a_', '--quiet', 'tulipy==0.4.0']' returned non-zero exit status 1.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a0/b6/eccd371ccc572a1a5f569e49ea44e2ff396f275ed3d3cd5635d34fe827e3/OctoBot-Evaluators-1.6.15.tar.gz#sha256=10953e44b77bdb58b8d8ed1c1d947d7fb0f1796079703227d1c66a76c6d02cab (from https://pypi.org/simple/octobot-evaluators/) (requires-python:>=3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement OctoBot-Evaluators==1.6.15 (from versions: 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.5.13, 1.5.14, 1.5.15, 1.5.16, 1.5.17, 1.5.18, 1.5.19, 1.5.21, 1.5.22, 1.5.23, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.6.12, 1.6.13, 1.6.14, 1.6.15)
ERROR: No matching distribution found for OctoBot-Evaluators==1.6.15
```

**Comment by GuillaumeDSM** [comment]
Hi @mertdogan 
OctoBot is requiring python 3.8, it will work when using this version

**Comment by mertdogan** [comment]
Thank you but at this page writes Python 3.9 supported. Yes i installed ccxt with 3.8. Thank you.

![image](https://user-images.githubusercontent.com/1324617/116208427-989fe900-a749-11eb-88bc-78bc2b3a4dfd.png)

**Comment by GuillaumeDSM** [comment]
ccxt is compatible with python3.9 but not OctoBot (yet) :) https://www.octobot.online/python_installation/
