### ISSUE TITLE
Bitvavo - Failed to update order : must be real number, not NoneType (TypeError)

### ISSUE THREAD

**Issue by M4ST3R1373** [Drakkar-Software/OctoBot#1700]
Hey community, I´m getting the following error while using OctoBot with Bitvavo:

Failed to update order : must be real number, not NoneType (TypeError)

2021-05-13 19:24:31 DEBUG  OrdersUpdater[bitvavo] events.py:81       Received update for ADA/EUR | BUY_MARKET | Price : 1.4353 | Quantity : 57.411581 | St$
2021-05-13 19:24:31 ERROR  ExchangePersonalData events.py:81       must be real number, not NoneType                                                       
Traceback (most recent call last):                                                                                                                         
  File "octobot_trading/personal_data/exchange_personal_data.py", line 117, in octobot_trading.personal_data.exchange_personal_data.ExchangePersonalData.h$
  File "octobot_trading/personal_data/orders/orders_manager.py", line 64, in upsert_order_from_raw                                                         
  File "octobot_trading/personal_data/orders/orders_manager.py", line 132, in _update_order_from_raw                                                       
  File "octobot_trading/personal_data/orders/orders_manager.py", line 134, in octobot_trading.personal_data.orders.orders_manager._update_order_from_raw   
  File "octobot_trading/personal_data/orders/order.py", line 302, in octobot_trading.personal_data.orders.order.Order.update_from_raw                      
  File "octobot_trading/personal_data/orders/order.py", line 315, in octobot_trading.personal_data.orders.order.Order.update_from_raw                      
  File "octobot_trading/personal_data/orders/order.py", line 89, in octobot_trading.personal_data.orders.order.Order.update

Latest stable Version.

**Comment by Herklos** [comment]
Hi @M4ST3R1373, thanks for reporting, I'll try to reproduce and fix it

**Comment by M4ST3R1373** [comment]
@Herklos if I can provide any further information let me know. We can do a Teams meeting if helpful.
Thank your for your help and your work on the project.
