### ISSUE TITLE
exception: BadRequest: gateio open order list limit allows 100 at most

### ISSUE THREAD

**Issue by proBieri** [Drakkar-Software/OctoBot#1866]
OS : Debian, running the Docker container
 
When connecting gateio as Exchange, fetching the orders does not fully work. Only the most recent orders are showing up. Thousends of AsyncJob errors are showing up.
 
```
2021-10-18 21:13:25 ERROR  AsyncJob-_open_orders_fetch_and_push events.py:81       Failed to run job action, exception: BadRequest: gateio open order list limit allows 100 at most (33 failures in a row) (BadRequest)
2021-10-18 21:13:30 DEBUG  ErrorsUploader       errors_uploader.py:91       Uploaded 1 errors
2021-10-18 21:13:32 ERROR  AsyncJob-_open_orders_fetch_and_push events.py:81       gateio open order list limit allows 100 at most
Traceback (most recent call last):
  File "octobot_commons/async_job.py", line 193, in octobot_commons.async_job.AsyncJob._run
  File "octobot_trading/personal_data/orders/channel/orders_updater.py", line 100, in _open_orders_fetch_and_push
  File "octobot_trading/exchanges/implementations/spot_ccxt_exchange.py", line 210, in get_open_orders
  File "octobot_trading/exchanges/connectors/ccxt_exchange.py", line 315, in get_open_orders
  File "octobot_trading/exchanges/connectors/ccxt_exchange.py", line 316, in octobot_trading.exchanges.connectors.ccxt_exchange.CCXTExchange.get_open_orders
  File "/opt/venv/lib/python3.8/site-packages/ccxt/async_support/gateio.py", line 1227, in fetch_open_orders
    return await self.fetch_orders_by_status('open', symbol, since, limit, params)
  File "/opt/venv/lib/python3.8/site-packages/ccxt/async_support/gateio.py", line 1245, in fetch_orders_by_status
    response = await self.privateSpotGetOrders(self.extend(request, params))
  File "/opt/venv/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 97, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/opt/venv/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 162, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/opt/venv/lib/python3.8/site-packages/ccxt/async_support/gateio.py", line 1345, in handle_errors
    raise Error(self.id + ' ' + message)
ccxt.base.errors.BadRequest: gateio open order list limit allows 100 at most
```

**Comment by codenut** [comment]
Hello @valouvaliavlo, thank you for fixing it. I am experiencing the same issue and I am new to using OctoBot. How to update the tentacles?

**Comment by valouvaliavlo** [comment]
> Hello @valouvaliavlo, thank you for fixing it. I am experiencing the same issue and I am new to using OctoBot. How to update the tentacles?

It will be officially included in 0.4.2, some days ;)

**Comment by nitrocon** [comment]
I have to reopen this issue, I get the same error with coinex
