### ISSUE TITLE
Timestamp for this request was 1000ms ahead of the server's time."} (4 failures in a row)

### ISSUE THREAD

**Issue by nathanp83** [Drakkar-Software/OctoBot#1883]
## Step 1: Have you searched for this issue before posting it?

Yes

## Step 2: Describe your environment
  * OS : Windows 10
  * Python Version: _____ (`python -V`)
  * In case you are not using a binary version:
    * Branch: Master | Dev
    * Last Commit ID: _____ (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
**Describe the bug**
Failed to run job action, exception: InvalidNonce: binanceus {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."} (4 failures in a row) (InvalidNonce)

**Expected behavior**
Should be no timestamp issues with using the suggested "Network Time" application.

### Steps to reproduce:

  1. Start OctoBot
  2. Enable Live Trading
  3. Wait for everything to load and observe the issue happening very frequently.
  
### Observed Results:

  * What happened?
  Timestamp for this request was 1000ms ahead of servers time
  * What did you expect to happen?
  In previous version of software, this never happened.

### Relevant code exceptions or logs:
 
```
2021-11-10 18:59:46 ERROR  AsyncJob-_open_orders_fetch_and_push events.py:81       binanceus {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
Traceback (most recent call last):
  File "octobot_commons\async_job.py", line 193, in octobot_commons.async_job.AsyncJob._run
  File "octobot_trading\personal_data\orders\channel\orders_updater.py", line 100, in _open_orders_fetch_and_push
  File "octobot_trading\exchanges\implementations\spot_ccxt_exchange.py", line 210, in get_open_orders
  File "octobot_trading\exchanges\connectors\ccxt_exchange.py", line 315, in get_open_orders
  File "octobot_trading\exchanges\connectors\ccxt_exchange.py", line 316, in octobot_trading.exchanges.connectors.ccxt_exchange.CCXTExchange.get_open_orders
  File "ccxt\async_support\binance.py", line 2370, in fetch_open_orders
  File "ccxt\async_support\binance.py", line 4169, in request
  File "ccxt\async_support\base\exchange.py", line 97, in fetch2
  File "ccxt\async_support\base\exchange.py", line 162, in fetch
  File "ccxt\async_support\binance.py", line 4149, in handle_errors
  File "ccxt\base\exchange.py", line 520, in throw_exactly_matched_exception
ccxt.base.errors.InvalidNonce: binanceus {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
2021-11-10 18:59:46 ERROR  AsyncJob-_open_orders_fetch_and_push events.py:81       Failed to run job action, exception: InvalidNonce: binanceus {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."} (3 failures in a row) (InvalidNonce)
2021-11-10 18:59:46 DEBUG  OctoBot Channel      logger.py:267      

2021-11-10 18:59:45 DEBUG  ErrorsUploader       errors_uploader.py:91       Uploaded 1 errors

![image](https://user-images.githubusercontent.com/46574910/141229848-64a57ae3-00c2-4cb9-9258-2e656f00721b.png)

![image](https://user-images.githubusercontent.com/46574910/141230077-57882dae-4d03-4f88-9873-00308146e095.png)

```

**Comment by valouvaliavlo** [comment]
Hi @nathanp83 
It's surely you ethernet connection. Are you on cable or wifi ?

**Comment by nathanp83** [comment]
Hi @valouvaliavlo 
Cable. Never had this issue with previous software version using the exact setup I have now.

**Comment by GuillaumeDSM** [comment]
Hi @nathanp83 !
Could you try this please ? Sometimes Windows clock can get out of sync.
https://docs.octobot.online/installation/installation-troubleshoot#time-synchronization

**Comment by nathanp83** [comment]
Hi GuillaumeDSM

I tried that method before installing NetTime and had no luck.  Trying again and the results::
PS C:\WINDOWS\system32> net stop w32time
The Windows Time service is not started.

More help is available by typing NET HELPMSG 3521.

PS C:\WINDOWS\system32> net start w32time
The Windows Time service is starting.
The Windows Time service was started successfully.

PS C:\WINDOWS\system32> w32tm /resync
Sending resync command to local computer
The command completed successfully.
PS C:\WINDOWS\system32> w32tm /query /status
Leap Indicator: 0(no warning)
Stratum: 4 (secondary reference - syncd by (S)NTP)
Precision: -23 (119.209ns per tick)
Root Delay: 0.0784478s
Root Dispersion: 8.6217400s
ReferenceId: 0x287706E4 (source IP:  40.119.6.228)
Last Successful Sync Time: 11/12/2021 9:06:31 AM
Source: time.windows.com,0x9
Poll Interval: 10 (1024s)

PS C:\WINDOWS\system32>

Still showing error in the logs:
![image](https://user-images.githubusercontent.com/46574910/141507425-988fc6c8-bba9-4f57-be02-841b671e1820.png)

**Comment by valouvaliavlo** [comment]
Have you test to do it from Windows GUI ?

**Comment by nathanp83** [comment]
> 
> 
> Have you test to do it from Windows GUI ?

I am sorry, I don't understand your question.

**Comment by valouvaliavlo** [comment]
> > Have you test to do it from Windows GUI ?
> 
> I am sorry, I don't understand your question.

![image](https://user-images.githubusercontent.com/28919459/141857102-b24a1092-2dda-48d0-820d-f92deaf7e51b.png)

**Comment by nathanp83** [comment]
![image](https://user-images.githubusercontent.com/46574910/141857425-566faf86-6792-4630-820b-a7368a5fd1e1.png)

**Comment by valouvaliavlo** [comment]
Can you test to manually set a date in the past then sync it ?

**Comment by nathanp83** [comment]
Tried that, still same issue.  Is it possible I need to open a port on my firewall?

**Comment by valouvaliavlo** [comment]
There is no option fo recvWindow in OctoBot for now.
Maybe can you try this : https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/544

**Comment by nathanp83** [comment]
Still happening:
![image](https://user-images.githubusercontent.com/46574910/142509499-493888bc-d00f-46e5-bfd9-082e927d7464.png)

**Comment by valouvaliavlo** [comment]
Can you try this : 
`"timeDifference": 2000,
"adjustForTimeDifference": True`

**Comment by nathanp83** [comment]
Same.  Tried both changes.

**Comment by nathanp83** [comment]
Is there a way to roll back a few versions, before this issue happened?  Or do I need to start from scratch.

**Comment by shizlkazizl** [comment]
Same issue in Docker on Mac OS(

**Comment by GuillaumeDSM** [comment]
Synching your Mac clock should fix the issue

**Comment by shizlkazizl** [comment]
Clock synchronization did not help.
I've tried using time.apple.com or time.euro.apple.com servers, but that didn't work.

**Comment by canyone2015** [comment]
I created a Python script that updates the system time every 15 minutes. This should solve the delay problem.
(Windows)

<details>
  <summary>UpdateSysTime.py</summary>

```python3
import ctypes
import os
import sys
import time


def run_as_admin(argv=None, debug=False):
    shell32 = ctypes.windll.shell32
    if argv is None and shell32.IsUserAnAdmin():
        return True
    if argv is None:
        argv = sys.argv
    if hasattr(sys, '_MEIPASS'):
        arguments = argv[1:]
    else:
        arguments = argv
    argument_line = ' '.join(arguments)
    executable = sys.executable
    if debug:
        print('Command line: ', executable, argument_line)
    ret = shell32.ShellExecuteW(None, "runas", executable, argument_line, None, 1)
    if int(ret) <= 32:
        return False
    return None


if __name__ == '__main__':
    ret = run_as_admin()
    if ret is True:
        print(f'Success(ret={ret}): admin.')
        try:
            loop = True
            while loop:
                try:
                    os.system('w32tm /resync')
                    os.system('w32tm /query /status')
                    time.sleep(60 * 15)
                except KeyboardInterrupt:
                    while True:
                        r = input('Exit program? [y/n]')
                        if r.lower() == 'y':
                            loop = False
                            break
                        elif r.lower() == 'n':
                            break
        except:
            pass
    elif ret is None:
        print(f'Error(ret={ret}): not admin.')

```

</details>

This script can be combined with the launch of Octobot.

<details>
  <summary>OctobotLaunch.py</summary>

```python3
import ctypes
import os
import subprocess
import sys
import time


def run_as_admin(argv=None, debug=False):
    shell32 = ctypes.windll.shell32
    if argv is None and shell32.IsUserAnAdmin():
        return True
    if argv is None:
        argv = sys.argv
    if hasattr(sys, '_MEIPASS'):
        arguments = argv[1:]
    else:
        arguments = argv
    argument_line = ' '.join(arguments)
    executable = sys.executable
    if debug:
        print('Command line: ', executable, argument_line)
    ret = shell32.ShellExecuteW(None, "runas", executable, argument_line, None, 1)
    if int(ret) <= 32:
        return False
    return None


if __name__ == '__main__':
    ret = run_as_admin()
    if ret is True:
        print(f'Success(ret={ret}): admin.')
        process = subprocess.Popen(["./OctoBot_windows_x64.exe"], stdin=subprocess.PIPE)
        print(f"PID: {process.pid}")
        try:
            loop = True
            while loop:
                try:
                    os.system('w32tm /resync')
                    os.system('w32tm /query /status')
                    time.sleep(60 * 15)
                except KeyboardInterrupt:
                    while True:
                        r = input('Exit program? [y/n]')
                        if r.lower() == 'y':
                            loop = False
                            process.terminate()
                            break
                        elif r.lower() == 'n':
                            break
        except:
            process.terminate()
        print('Process terminated')
    elif ret is None:
        print(f'Error(ret={ret}): not admin.')

```

</details>

Thus, Octobot will be launched, and the system time will be updated every 15 minutes.
