### ISSUE TITLE
backtesting from strategy page throws an error

### ISSUE THREAD

**Issue by Noilly-Prat** [Drakkar-Software/OctoBot#1885]
## Step 1: Have you search for this issue before posting it?
yes

## Step 2: Describe your environment
using the Oketo deployment.
So I would say 
  * OS : Linux
  * Python Version/ 3.8
  * In case you are not using a binary version:
    * Branch: Master 
    * Last Commit ID: N/A
 
## Step 3: Describe the problem:
**Describe the bug**
From a strategy configuration page (tested with SimpleStrategyEvaluator under the DailyTrading mode), I canoot backtest the configuration.
I got the error
`list indices must be integers or slices, not str (TypeError)`
I tried with binance and bitfinex

Extra: backtesting from the backtesting page works well with the same datasets

**Expected behavior**
Clicking on Backtesting from the strategy configuration page should work

### Steps to reproduce:

  1. Go to a strategy configuration page
  2. Try to backtest that config
  3. ERROR
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:
![capture2](https://user-images.githubusercontent.com/78227449/142016169-1b17d863-85e9-40a9-ba79-9fdb1ada5568.png)
 
```
octobot-0octobotTraceback (most recent call last):
octobot-0octobot  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
octobot-0octobot    response = self.full_dispatch_request()
octobot-0octobot  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
octobot-0octobot    rv = self.handle_user_exception(e)
octobot-0octobot  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
octobot-0octobot    reraise(exc_type, exc_value, tb)
octobot-0octobot  File "/opt/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
octobot-0octobot    raise value
octobot-0octobot  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
octobot-0octobot    rv = self.dispatch_request()
octobot-0octobot  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
octobot-0octobot    return self.view_functions[rule.endpoint](**req.view_args)
octobot-0octobot  File "/octobot/tentacles/Services/Interfaces/web_interface/login/web_login_manager.py", line 67, in decorated_view
octobot-0octobot    return func(*args, **kwargs)
octobot-0octobot  File "/octobot/tentacles/Services/Interfaces/web_interface/controllers/backtesting.py", line 41, in backtesting
octobot-0octobot    success, reply = models.start_backtesting_using_specific_files(data["files"],
octobot-0octobot 2021-11-16 15:40:20,281 ERROR    WebInterfaceErrorHandler Error when displaying page: list indices must be integers or slices, not str (TypeError)
```

Same logs with the timestamp
```
2021-11-16 15:40:20.28 UTCoctobot-0octobotTraceback (most recent call last):
2021-11-16 15:40:20.28 UTCoctobot-0octobot  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
2021-11-16 15:40:20.28 UTCoctobot-0octobot    response = self.full_dispatch_request()
2021-11-16 15:40:20.28 UTCoctobot-0octobot  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
2021-11-16 15:40:20.28 UTCoctobot-0octobot    rv = self.handle_user_exception(e)
2021-11-16 15:40:20.28 UTCoctobot-0octobot  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
2021-11-16 15:40:20.28 UTCoctobot-0octobot    reraise(exc_type, exc_value, tb)
2021-11-16 15:40:20.28 UTCoctobot-0octobot  File "/opt/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
2021-11-16 15:40:20.28 UTCoctobot-0octobot    raise value
2021-11-16 15:40:20.28 UTCoctobot-0octobot  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
2021-11-16 15:40:20.28 UTCoctobot-0octobot    rv = self.dispatch_request()
2021-11-16 15:40:20.28 UTCoctobot-0octobot  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
2021-11-16 15:40:20.28 UTCoctobot-0octobot    return self.view_functions[rule.endpoint](**req.view_args)
2021-11-16 15:40:20.28 UTCoctobot-0octobot  File "/octobot/tentacles/Services/Interfaces/web_interface/login/web_login_manager.py", line 67, in decorated_view
2021-11-16 15:40:20.28 UTCoctobot-0octobot    return func(*args, **kwargs)
2021-11-16 15:40:20.28 UTCoctobot-0octobot  File "/octobot/tentacles/Services/Interfaces/web_interface/controllers/backtesting.py", line 41, in backtesting
2021-11-16 15:40:20.28 UTCoctobot-0octobot    success, reply = models.start_backtesting_using_specific_files(data["files"],
2021-11-16 15:40:20.28 UTCoctobot-0octobot 2021-11-16 15:40:20,281 ERROR    WebInterfaceErrorHandler Error when displaying page: list indices must be integers or slices, not str (TypeError)
```

**Comment by valouvaliavlo** [comment]
should fixed in 0.4.2

**Comment by blueyed** [comment]
This can be closed I assume.
