### ISSUE TITLE
tentacles.Services.Interfaces.web_interface app.py:1891

### ISSUE THREAD

**Issue by isaack0815** [Drakkar-Software/OctoBot#1929]
## Describe my environment
  * OS : Ubuntu 20
  * Python Version: 3.8.10 (`python -V`)
  * In case you are not using a binary version:
    * Branch: Master | Dev
 
## Describe the problem:
Hi there,
have with this command:
```
docker run -itd --name OctoBot -p 80:5001 -v $(pwd)/user:/octobot/user -v $(pwd)/tentacles:/octobot/tentacles -v $(pwd)/logs:/octobot /logs drakkarsoftware/octobot:stable
```
OctoBot installed and called.
As soon as I click on accounts I only get the error message.
The logs say the following
 
```
2022-02-18 11:23:56 ERROR  tentacles.Services.Interfaces.web_interface app.py:1891     Exception on /accounts [GET]
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/octobot/tentacles/Services/Interfaces/web_interface/login/web_login_manager.py", line 67, in decorated_view
    return func(*args, **kwargs)
  File "/octobot/tentacles/Services/Interfaces/web_interface/controllers/configuration.py", line 124, in accounts
    service_list = models.get_services_list()
  File "/octobot/tentacles/Services/Interfaces/web_interface/models/configuration.py", line 513, in get_services_list
    if srv.get_required_config():
  File "/octobot/tentacles/Services/Services_bases/webhook_service/webhook.py", line 104, in get_required_config
    return [services_constants.CONFIG_ENABLE_NGROK, services_constants.CONFIG_NGROK_TOKEN]
AttributeError: module 'octobot_services.constants' has no attribute 'CONFIG_ENABLE_NGROK'
2022-02-18 11:23:56 ERROR  WebInterfaceErrorHandler errors.py:34       module 'octobot_services.constants' has no attribute 'CONFIG_ENABLE_NGROK'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/octobot/tentacles/Services/Interfaces/web_interface/login/web_login_manager.py", line 67, in decorated_view
    return func(*args, **kwargs)
  File "/octobot/tentacles/Services/Interfaces/web_interface/controllers/configuration.py", line 124, in accounts
    service_list = models.get_services_list()
  File "/octobot/tentacles/Services/Interfaces/web_interface/models/configuration.py", line 513, in get_services_list
    if srv.get_required_config():
  File "/octobot/tentacles/Services/Services_bases/webhook_service/webhook.py", line 104, in get_required_config
    return [services_constants.CONFIG_ENABLE_NGROK, services_constants.CONFIG_NGROK_TOKEN]
AttributeError: module 'octobot_services.constants' has no attribute 'CONFIG_ENABLE_NGROK'
2022-02-18 11:23:56 ERROR  WebInterfaceErrorHandler errors.py:34       Error when displaying page: module 'octobot_services.constants' has no attribute 'CONFIG_ENABLE_NGROK' (AttributeError)

```

**Comment by Herklos** [comment]
Hi @isaack0815, it should be fixed in recent versions :wink:
