### ISSUE TITLE
Error: 'octobot_trading.personal_data.portfolios.assets.spot_asset.SpotAsset' object is not subscriptable (TypeError).

### ISSUE THREAD

**Issue by danieljamesbertrand** [Drakkar-Software/OctoBot#1942]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/Drakkar-Software/OctoBot/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment
  * OS : [Windows, Ubuntu, Debian, Raspbian...] 
  * Python Version: _____ (`python -V`)
  * In case you are not using a binary version:
    * Branch: Master | Dev
    * Last Commit ID: _____ (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
**Describe the bug**

**Expected behavior**

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:
 
```
// paste your log here
```

**Comment by danieljamesbertrand** [comment]
OS : Windows
Python 3.8.7

<html>
<body>


2022-04-08 03:28:15 | ERROR | WebInterfaceErrorHandler | Error when displaying page: 'octobot_trading.personal_data.portfolios.assets.spot_asset.SpotAsset' object is not subscriptable (TypeError)
-- | -- | -- | --
2022-04-08 03:27:59 | ERROR | WebInterfaceErrorHandler | Error when displaying page: 'octobot_trading.personal_data.portfolios.assets.spot_asset.SpotAsset' object is not subscriptable (TypeError)


</body>
</html>

**Comment by dadam247** [comment]
OS: Ubuntu
Python versin: 3.8.10

Ostobot cant'see my portfolio.




TypeError: 'octobot_trading.personal_data.portfolios.assets.spot_asset.SpotAsset' object is not subscriptable
2022-05-02 00:06:00 ERROR  WebInterfaceErrorHandler errors.py:34       'octobot_trading.personal_data.portfolios.assets.spot_asset.SpotAsset' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/Desktop/OctoBot/tentacles/Services/Interfaces/web_interface/login/web_login_manager.py", line 67, in decorated_view
    return func(*args, **kwargs)
  File "/root/Desktop/OctoBot/tentacles/Services/Interfaces/web_interface/controllers/trading.py", line 31, in portfolio
    displayed_portfolio = models.get_exchange_holdings_per_symbol()
  File "/root/Desktop/OctoBot/tentacles/Services/Interfaces/web_interface/models/trading.py", line 96, in get_exchange_holdings_per_symbol
    _add_exchange_portfolio(portfolio, trading_api.get_exchange_name(exchange_manager), holdings_per_symbol)
  File "/root/Desktop/OctoBot/tentacles/Services/Interfaces/web_interface/models/trading.py", line 73, in _add_exchange_portfolio
    total_amount = amounts[commons_constants.PORTFOLIO_TOTAL]
TypeError: 'octobot_trading.personal_data.portfolios.assets.spot_asset.SpotAsset' object is not subscriptable

**Comment by dadam247** [comment]
OS: Ubuntu
Python versin: 3.8.10

Ostobot cant'see my portfolio.




TypeError: 'octobot_trading.personal_data.portfolios.assets.spot_asset.SpotAsset' object is not subscriptable
2022-05-02 00:06:00 ERROR  WebInterfaceErrorHandler errors.py:34       'octobot_trading.personal_data.portfolios.assets.spot_asset.SpotAsset' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/Desktop/OctoBot/tentacles/Services/Interfaces/web_interface/login/web_login_manager.py", line 67, in decorated_view
    return func(*args, **kwargs)
  File "/root/Desktop/OctoBot/tentacles/Services/Interfaces/web_interface/controllers/trading.py", line 31, in portfolio
    displayed_portfolio = models.get_exchange_holdings_per_symbol()
  File "/root/Desktop/OctoBot/tentacles/Services/Interfaces/web_interface/models/trading.py", line 96, in get_exchange_holdings_per_symbol
    _add_exchange_portfolio(portfolio, trading_api.get_exchange_name(exchange_manager), holdings_per_symbol)
  File "/root/Desktop/OctoBot/tentacles/Services/Interfaces/web_interface/models/trading.py", line 73, in _add_exchange_portfolio
    total_amount = amounts[commons_constants.PORTFOLIO_TOTAL]
TypeError: 'octobot_trading.personal_data.portfolios.assets.spot_asset.SpotAsset' object is not subscriptable

**Comment by Herklos** [comment]
It should be fixed with a more recent OctoBot version.
