### ISSUE TITLE
During order create, type error for unsupported operand type(s) for *: 'decimal.Decimal' and 'float'

### ISSUE THREAD

**Issue by AndrewSerra** [Drakkar-Software/OctoBot#1993]
## Step 1: Have you search for this issue before posting it?
Yes

## Step 2: Describe your environment
  * OS : [Alpine Linux on Raspberry Pi, deployed with docker] 
  * Python Version: 3.8 (`python -V`)
 
## Step 3: Describe the problem:
**Describe the bug**
When there is an order to be created, the following error occurs:
```
2022-07-15 04:15:54,203 ERROR    DailyTradingModeConsumer [<class 'decimal.ConversionSyntax'>]
Traceback (most recent call last):
  File "/octobot/tentacles/Trading/Mode/daily_trading_mode/daily_trading.py", line 320, in create_new_orders
    quantity = trading_personal_data.decimal_add_dusts_to_quantity_if_necessary(quantity, price, symbol_market,
  File "octobot_trading/personal_data/orders/decimal_order_adapter.py", line 243, in octobot_trading.personal_data.orders.decimal_order_adapter.decimal_add_dusts_to_quantity_if_necessary
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
 2022-07-15 04:15:54,209 ERROR    DailyTradingModeConsumer Failed to create order : [<class 'decimal.ConversionSyntax'>]. (InvalidOperation)
```
This happens with every order trying to be created. I have checked the markets that have the option to buy/sell. The "view only" ones are not in my currency list.

**Expected behavior**
To create a trade using Coinbase Pro.

### Steps to reproduce:

  1. Pull docker image and start it
  2. Add coinbase pro credentials
  3. Add currencies
  4. Enter real trading
  5. Wait for data to fill in
  
### Observed Results:

  * What happened?
As soon as there is a possible trade, the error shows up during order creation. Data can be pulled in for graphs, and the currency states update.
  * What did you expect to happen?
To have the order be created for the analysis and trade settings.

### Relevant code exceptions or logs:

<img width="1594" alt="Screen Shot 2022-07-15 at 12 51 45 AM" src="https://user-images.githubusercontent.com/7320235/179153143-9f329697-2934-4944-89e2-1c8d2e66b1d9.png">
 
```
 2022-07-15 04:15:53,889 ERROR    root                 <class 'TypeError'>: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
NoneType: None
Exception ignored in: 'octobot_trading.exchanges.util.exchange_market_status_fixer.ExchangeMarketStatusFixer._fix_market_status_limits_with_price'
Traceback (most recent call last):
  File "/octobot/tentacles/Trading/Mode/daily_trading_mode/daily_trading.py", line 320, in create_new_orders
    quantity = trading_personal_data.decimal_add_dusts_to_quantity_if_necessary(quantity, price, symbol_market,
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
 2022-07-15 04:15:53,896 ERROR    DailyTradingModeConsumer [<class 'decimal.ConversionSyntax'>]
Traceback (most recent call last):
  File "/octobot/tentacles/Trading/Mode/daily_trading_mode/daily_trading.py", line 320, in create_new_orders
    quantity = trading_personal_data.decimal_add_dusts_to_quantity_if_necessary(quantity, price, symbol_market,
  File "octobot_trading/personal_data/orders/decimal_order_adapter.py", line 243, in octobot_trading.personal_data.orders.decimal_order_adapter.decimal_add_dusts_to_quantity_if_necessary
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
 2022-07-15 04:15:53,903 ERROR    DailyTradingModeConsumer Failed to create order : [<class 'decimal.ConversionSyntax'>]. (InvalidOperation)
 2022-07-15 04:15:53,956 INFO     DailyTradingModeProducer [ETH/USD] new state: NEUTRAL
 2022-07-15 04:15:54,052 INFO     DailyTradingModeProducer [AVAX/USD] new state: SHORT
 2022-07-15 04:15:54,162 INFO     DailyTradingModeProducer [SOL/ETH] new state: SHORT
 2022-07-15 04:15:54,187 ERROR    root                 
NoneType: None
 2022-07-15 04:15:54,196 ERROR    root                 <class 'TypeError'>: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
NoneType: None
Exception ignored in: 'octobot_trading.exchanges.util.exchange_market_status_fixer.ExchangeMarketStatusFixer._fix_market_status_limits_with_price'
Traceback (most recent call last):
  File "/octobot/tentacles/Trading/Mode/daily_trading_mode/daily_trading.py", line 320, in create_new_orders
    quantity = trading_personal_data.decimal_add_dusts_to_quantity_if_necessary(quantity, price, symbol_market,
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
 2022-07-15 04:15:54,203 ERROR    DailyTradingModeConsumer [<class 'decimal.ConversionSyntax'>]
Traceback (most recent call last):
  File "/octobot/tentacles/Trading/Mode/daily_trading_mode/daily_trading.py", line 320, in create_new_orders
    quantity = trading_personal_data.decimal_add_dusts_to_quantity_if_necessary(quantity, price, symbol_market,
  File "octobot_trading/personal_data/orders/decimal_order_adapter.py", line 243, in octobot_trading.personal_data.orders.decimal_order_adapter.decimal_add_dusts_to_quantity_if_necessary
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
 2022-07-15 04:15:54,209 ERROR    DailyTradingModeConsumer Failed to create order : [<class 'decimal.ConversionSyntax'>]. (InvalidOperation)
```

**Comment by GuillaumeDSM** [comment]
The issue will be fixed in the next version.
