### ISSUE TITLE
mark price is not available on kucoin

### ISSUE THREAD

**Issue by t-900-a** [Drakkar-Software/OctoBot#2198]
kucoin doesn't seem to be working with the dca trading mode

```
 2023-01-24 07:58:27,388 ERROR    DCATradingModeConsumer Failed to create order : Can't get the necessary price data to create a new order on the 24/01/23 07:53 (timestamp: 1674564807.362): mark price is not available. Order: None
 2023-01-24 07:58:27,388 ERROR    DCATradingModeConsumer Can't get the necessary price data to create a new order on the 24/01/23 07:53 (timestamp: 1674564807.362): mark price is not available
Traceback (most recent call last):
  File "octobot_trading\personal_data\orders\order_util.py", line 112, in octobot_trading.personal_data.orders.order_util.get_up_to_date_price
  File "octobot_trading\exchange_data\prices\prices_manager.py", line 107, in get_mark_price
  File "octobot_trading\exchange_data\prices\prices_manager.py", line 101, in octobot_trading.exchange_data.prices.prices_manager.PricesManager.get_mark_price
  File "asyncio\tasks.py", line 501, in wait_for
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user1\Downloads\tentacles\Trading\Mode\dca_trading_mode\dca_trading.py", line 43, in create_new_orders
    await trading_personal_data.get_pre_order_data(self.exchange_manager, symbol=symbol,
  File "octobot_trading\personal_data\orders\order_util.py", line 124, in get_pre_order_data
  File "octobot_trading\personal_data\orders\order_util.py", line 115, in get_up_to_date_price
asyncio.exceptions.TimeoutError: Can't get the necessary price data to create a new order on the 24/01/23 07:53 (timestamp: 1674564807.362): mark price is not available
```

**Comment by GuillaumeDSM** [comment]
Hey @t-900-a, 
thanks for reporting the issue, what version of OctoBot are you using ?
