### ISSUE TITLE
[OrderManager] "Timed Out" raised during _update_orders_status

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot#252]
2018-06-20 16:43:18 ERROR  OrdersManager        orders_manager.py:131      Error when updating orders: Timed out

**Comment by Herklos** [comment]
Traceback (most recent call last):
  File "/home/herklos/OctoBot/trading/trader/modes/abstract_mode_decider.py", line 72, in finalize
    self.create_state()
  File "/home/herklos/OctoBot/tentacles/Trading/Mode/Default/daily_trading_mode.py", line 262, in create_state
    self._set_state(EvaluatorStates.LONG)
  File "/home/herklos/OctoBot/tentacles/Trading/Mode/Default/daily_trading_mode.py", line 301, in _set_state
    self.create_final_state_orders(evaluator_notification, self.trading_mode.get_only_creator_key())
  File "/home/herklos/OctoBot/trading/trader/modes/abstract_mode_decider.py", line 34, in create_final_state_orders
    creator_key)
  File "/home/herklos/OctoBot/trading/trader/modes/abstract_mode_decider.py", line 111, in create_order_if_possible
    self._push_order_notification_if_possible(new_orders, evaluator_notification)
  File "/home/herklos/OctoBot/trading/trader/modes/abstract_mode_decider.py", line 117, in _push_order_notification_if_possible
    order.get_order_notifier().notify(notification)
  File "/home/herklos/OctoBot/trading/trader/order_notifier.py", line 15, in notify
    self.notifier.notify_create(evaluator_notification, orders)
  File "/home/herklos/OctoBot/tools/notifications.py", line 180, in notify_create
    self.telegram_notification_factory(content)
  File "/home/herklos/OctoBot/tools/notifications.py", line 74, in telegram_notification_factory
    result = telegram_service.send_message(message)
  File "/home/herklos/OctoBot/services/telegram_service.py", line 68, in send_message
    self.telegram_api.send_message(chat_id=self.chat_id, text=content)
  File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 85, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 272, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 192, in _request_wrapper
    raise TimedOut()
telegram.error.TimedOut: Timed out
