### ISSUE TITLE
Yobit Exchange will not pull history, or trade. 

### ISSUE THREAD

**Issue by KhryptorGraphics** [Drakkar-Software/OctoBot#2741]
When pulling historical data from yobit.
2024-09-02 19:04:36 Traceback (most recent call last):
2024-09-02 19:04:36   File "/opt/venv/lib/python3.10/site-packages/octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py", line 275, in get_symbol_prices
2024-09-02 19:04:36     await self.client.fetch_ohlcv(symbol, time_frame.value, limit=limit, since=since, params=kwargs)
2024-09-02 19:04:36   File "/opt/venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 751, in fetch_ohlcv
2024-09-02 19:04:36     raise NotSupported(self.id + ' fetchOHLCV() is not supported yet' + message)
2024-09-02 19:04:36 ccxt.base.errors.NotSupported: yobit fetchOHLCV() is not supported yet. If you want to build OHLCV candles from trade executions data, visit https://github.com/ccxt/ccxt/tree/master/examples/ and see "build-ohlcv-bars" file
2024-09-02 19:04:36 
2024-09-02 19:04:36 During handling of the above exception, another exception occurred:
2024-09-02 19:04:36 
2024-09-02 19:04:36 Traceback (most recent call last):
2024-09-02 19:04:36   File "/octobot/tentacles/Backtesting/collectors/exchanges/exchange_history_collector/history_collector.py", line 86, in start
2024-09-02 19:04:36     await self.get_ohlcv_history(self.exchange_name, symbol, time_frame)
2024-09-02 19:04:36   File "/octobot/tentacles/Backtesting/collectors/exchanges/exchange_history_collector/history_collector.py", line 158, in get_ohlcv_history
2024-09-02 19:04:36     candles = await self.exchange.get_symbol_prices(symbol_id, time_frame)
2024-09-02 19:04:36   File "/opt/venv/lib/python3.10/site-packages/octobot_trading/exchanges/types/rest_exchange.py", line 505, in get_symbol_prices
2024-09-02 19:04:36     return await self.connector.get_symbol_prices(symbol=symbol, time_frame=time_frame, limit=limit, **kwargs)
2024-09-02 19:04:36   File "/opt/venv/lib/python3.10/site-packages/octobot_trading/exchanges/connectors/ccxt/ccxt_client_util.py", line 235, in converted_ccxt_common_errors_wrapper
2024-09-02 19:04:36     return await f(*args, **kwargs)
2024-09-02 19:04:36   File "/opt/venv/lib/python3.10/site-packages/octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py", line 278, in get_symbol_prices
2024-09-02 19:04:36     raise octobot_trading.errors.NotSupported
2024-09-02 19:04:36 octobot_trading.errors.NotSupported

**Comment by Herklos** [comment]
Hi @KhryptorGraphics, thanks for reporting.
OctoBot supported exchanges list is available here https://www.octobot.cloud/en/guides/exchanges.
As Yobit is not mentioned here we cannot guarantee it will work (with your logs it seems not).
You can ask for the support of Yobit here https://feedback.octobot.cloud/open-source
