### ISSUE TITLE
how to use ccxt with proxy?

### ISSUE THREAD

**Issue by touhoufan2024** [Drakkar-Software/OctoBot#2758]
i need proxy; this is ccxt doc

https://docs.ccxt.com/#/?id=proxy

**Comment by Herklos** [comment]
https://feedback.octobot.cloud/

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Herklos** [comment]
Hello, thanks for your suggestion.

Here is how to use our new proxy feature: https://www.octobot.cloud/en/guides/octobot-advanced-usage/using-octobot-with-a-proxy

**Comment by qdwds** [comment]
1.vim ~/.zshrc

2.# proxy
export EXCHANGE_HTTP_PROXY_AUTHENTICATED_URL=http://127.0.0.1:1087
#export EXCHANGE_HTTPS_PROXY_AUTHENTICATED_URL=https://127.0.0.1:1087
export EXCHANGE_SOCKS_PROXY_AUTHENTICATED_URL=socks5h://127.0.0.1:1086


3.source ~/.zshrc

2025-06-21 21:46:24,048 ERROR    CCXTConnector[binance] Exchange configuration is invalid : please check your configuration ! (TypeError: 'NoneType' object is not callable)
 2025-06-21 21:46:24,072 ERROR    OctoBotChannelTradingConsumer 'NoneType' object is not callable
Traceback (most recent call last):
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/connectors/ccxt/ccxt_client_util.py", line 83, in create_client
    client = instantiate_exchange(
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/connectors/ccxt/ccxt_client_util.py", line 145, in instantiate_exchange
    _use_proxy_if_necessary(client, proxy_config)
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/connectors/ccxt/ccxt_client_util.py", line 314, in _use_proxy_if_necessary
    proxy_url = proxy_config.get_proxy_url()
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/octobot_channel_consumer.py", line 84, in _handle_creation
    await exchange_builder.build()
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/exchange_builder.py", line 52, in build
    raise e
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/exchange_builder.py", line 48, in build
    await self._build_exchange_manager()
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/exchange_builder.py", line 70, in _build_exchange_manager
    await self.exchange_manager.initialize(exchange_config_by_exchange=self.exchange_config_by_exchange)
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/util/initializable.py", line 28, in initialize
    await self.initialize_impl(**kwargs)
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/exchange_manager.py", line 93, in initialize_impl
    await exchanges.create_exchanges(self, exchange_config_by_exchange)
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/exchange_factory.py", line 36, in create_exchanges
    await create_real_exchange(exchange_manager, exchange_config_by_exchange)
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/exchange_factory.py", line 57, in create_real_exchange
    await _create_rest_exchange(exchange_manager, exchange_config_by_exchange)
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/exchange_factory.py", line 136, in _create_rest_exchange
    await _search_and_create_rest_exchange(exchange_manager, exchange_config_by_exchange)
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/exchange_factory.py", line 172, in _search_and_create_rest_exchange
    exchange_manager.exchange = rest_exchange_class(
  File "/Users/loser/Desktop/OctoBot/tentacles/Trading/Exchange/binance/binance_exchange.py", line 115, in __init__
    super().__init__(config, exchange_manager, exchange_config_by_exchange, connector_class=connector_class)
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/types/rest_exchange.py", line 152, in __init__
    self.connector = self._create_connector(config, exchange_manager, connector_class)
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/types/rest_exchange.py", line 156, in _create_connector
    return (connector_class or self.DEFAULT_CONNECTOR_CLASS)(
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py", line 87, in __init__
    self._create_client()
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py", line 247, in _create_client
    self.client, self.is_authenticated = self._client_factory(force_unauth)
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py", line 254, in _client_factory
    return ccxt_client_util.create_client(
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/connectors/ccxt/ccxt_client_util.py", line 96, in create_client
    return unauthenticated_exchange_fallback(e), False
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/connectors/ccxt/ccxt_connector.py", line 272, in unauthenticated_exchange_fallback
    return ccxt_client_util.get_unauthenticated_exchange(
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/connectors/ccxt/ccxt_client_util.py", line 132, in get_unauthenticated_exchange
    return instantiate_exchange(
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/connectors/ccxt/ccxt_client_util.py", line 145, in instantiate_exchange
    _use_proxy_if_necessary(client, proxy_config)
  File "/Users/loser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/octobot_trading/exchanges/connectors/ccxt/ccxt_client_util.py", line 314, in _use_proxy_if_necessary
    proxy_url = proxy_config.get_proxy_url()
TypeError: 'NoneType' object is not callable
 2025-06-21 21:46:24,086 ERROR    OctoBotChannelTradingConsumer Error when creating a new binance exchange connexion: TypeError 'NoneType' object is not callable (error: TypeError)
 2025-06-21 21:46:29,091 WARNING  WebService           Impossible to find local web interface url, using default instead: [Errno 8] nodename nor servname provided, or not known (gaierror)
 2025-06-21 21:46:29,092 INFO     WebService           Interface successfully initialized and accessible at: http://127.0.0.1:5001.
 2025-06-21 21:46:34,291 WARNING  WebInterface         Impossible to open automatically web interface: [Errno 8] nodename nor servname provided, or not known (gaierror)

4. I configured a global proxy, but when I run python start.py, an error message appears, indicating that the proxy is invalid. Is there any other way to configure it? Can I configure the proxy in config.json? I did not find the corresponding method in the documentation.
