### ISSUE TITLE
"Error with websocket" logged in WebInterface.

### ISSUE THREAD

**Issue by yrammos** [Drakkar-Software/OctoBot#2834]
## Step 1: Have you searched for this issue before posting it?

Yes.

## Step 2: Describe your environment
  * OS : Ubuntu 24.04.1 LTS
  * Python Version: 3.10.16
  * Server version: Apache/2.4.58 (Ubuntu)
  * In case you are not using a binary version:
    * Branch: `master`
    * Last Commit ID: `30809a5b`

I am using the web app behind a simple Apache reverse proxy.

## Step 3: Describe the problem:

The attached error log is produced every time I click on the navigation bar (Home, Trading, Portfolio, etc.).

```
2024-12-25 22:35:37,499 ERROR    WebInterface         AbstractWebSocketNamespaceNotifier.on_disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/me/mambaforge/envs/octobot/lib/python3.10/site-packages/flask_socketio/__init__.py", line 838, in _handle_event
    ret = handler(*args)
TypeError: AbstractWebSocketNamespaceNotifier.on_disconnect() takes 1 positional argument but 2 were given
```

### Steps to reproduce:

  1.  Open my self-hosted OctoBot.
  2.  Navigate between the main app pages (Home, Trading, etc.).
  
### Observed Results:

  * The attached error message is logged upon each page transition.
  * The functionality of the app does not seem to be affected. However the presence of the error is disconcerting as long as its causes are unknown. I haven’t set up any automations yet, so I cannot tell whether they are affected. 

### Note:

Might the error be related to the handling of web sockets by the reverse proxy? Do websockets use a specific URL path (e.g. `/websocket`?

```
2024-12-25 22:35:37,499 ERROR    WebInterface         AbstractWebSocketNamespaceNotifier.on_disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/me/mambaforge/envs/octobot/lib/python3.10/site-packages/flask_socketio/__init__.py", line 838, in _handle_event
    ret = handler(*args)
TypeError: AbstractWebSocketNamespaceNotifier.on_disconnect() takes 1 positional argument but 2 were given
```

**Comment by yrammos** [comment]
UPDATE:

I realized that the socket URL path in my reverse proxy settings was incorrect; it should be `/socket.io`. 

Appending my Apache settings for future reference:

```
ProxyPass          /socket.io/    ws://127.0.0.1:5001/socket.io
ProxyPassReverse    /socket.io/    ws://127.0.0.1:5001/socket.io
ProxyPass       / http://127.0.0.1:5001/
ProxyPassReverse      / http://127.0.0.1:5001/
```
