### ISSUE TITLE
Error when starting backtesting: 'backtesting'

### ISSUE THREAD

**Issue by sandoche** [Drakkar-Software/OctoBot#399]
* OS : Windows 10
* Python version: 2.7
* Release: Open Beta - 0.2.0

I first download the backtesting data.
Then when I run the backtesting I receive this error:
`"Error when starting backtesting: 'backtesting'"`

Here are the logs
```
 2018-09-16 16:15:18,983 ERROR    DataCollectorWebInterfaceModel 'backtesting'
Traceback (most recent call last):
  File "interfaces\web\models\backtesting.py", line 30, in start_backtesting_using_specific_files
  File "backtesting\backtester.py", line 8, in __init__
  File "backtesting\backtesting_util.py", line 33, in get_standalone_backtesting_bot
  File "backtesting\backtesting_util.py", line 28, in create_blank_config_using_loaded_one
  File "backtesting\backtesting_util.py", line 71, in add_config_default_backtesting_values
KeyError: 'backtesting'
 2018-09-16 16:15:20,896 ERROR    DataCollectorWebInterfaceModel 'backtesting'
Traceback (most recent call last):
  File "interfaces\web\models\backtesting.py", line 30, in start_backtesting_using_specific_files
  File "backtesting\backtester.py", line 8, in __init__
  File "backtesting\backtesting_util.py", line 33, in get_standalone_backtesting_bot
  File "backtesting\backtesting_util.py", line 28, in create_blank_config_using_loaded_one
  File "backtesting\backtesting_util.py", line 71, in add_config_default_backtesting_values
KeyError: 'backtesting'
 2018-09-16 16:18:40,801 ERROR    DataCollectorWebInterfaceModel 'backtesting'
Traceback (most recent call last):
  File "interfaces\web\models\backtesting.py", line 30, in start_backtesting_using_specific_files
  File "backtesting\backtester.py", line 8, in __init__
  File "backtesting\backtesting_util.py", line 33, in get_standalone_backtesting_bot
  File "backtesting\backtesting_util.py", line 28, in create_blank_config_using_loaded_one
  File "backtesting\backtesting_util.py", line 71, in add_config_default_backtesting_values
KeyError: 'backtesting'
```

**Comment by GuillaumeDSM** [comment]
Hi Sandoche,
Thanks for using OctoBot and for the detailed logs ! 
I just reproduced your problem, i will fix the code asap.

On your side, you can have the backtesting with a quick workaround:
* Open your config.json file (with any text editor) and add the following element just before the **"crypto-currencies":{** line:
```json
"backtesting":{
      "enabled": false,
      "files": []
  },
```
* Restart OctoBot and it should work

Don't hesitate if you have any other question / problem with OctoBot !

Guillaume

**Comment by sandoche** [comment]
Thanks I'll give a try

**Comment by GuillaumeDSM** [comment]
Since no news, I will consider the problem as solved
