### ISSUE TITLE
Error when trying to enable live trader

### ISSUE THREAD

**Issue by muc1** [Drakkar-Software/OctoBot#407]
>  2018-09-30 03:13:45,722 ERROR    OctoBot Launcher     OctoBot Exception : binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
Traceback (most recent call last):
  File "site-packages\ccxt\base\exchange.py", line 385, in fetch
  File "site-packages\requests\models.py", line 939, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url:

**Comment by GuillaumeDSM** [comment]
Perfect :)
Yes that's also what we do too when it happens.
