### ISSUE TITLE
OctoBot Exception : 'refresh_rate_seconds'

### ISSUE THREAD

**Issue by blizzer3** [Drakkar-Software/OctoBot#411]
## Step 2: Describe your environment
  * OS : [Windows, Ubuntu, Debian, Raspbian...] 
Windows 10
  * Python Version: _____ (`python -V`)
3.6
  * Branch: Master | Dev
Master
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
**Describe the bug**
it wont work, cant get into the web ui or the bot to function properly 
check my error 

**Expected behavior**
I was hoping to start the program and use it ...
### Steps to reproduce:
Download launcher on Windows 10
Install it
Start it and i get that bug

```
2018-10-01 23:55:12,633 ERROR    OctoBot Launcher     OctoBot Exception : 'refresh_rate_seconds'
Traceback (most recent call last):
  File "tools\commands.py", line 70, in start_bot
  File "octobot.py", line 159, in create_evaluation_threads
  File "octobot.py", line 175, in _create_symbol_threads_managers
  File "evaluator\evaluator_creator.py", line 87, in create_real_time_ta_evals
  File "C:\Users\greed\Downloads\Trading\test\tentacles\Evaluator\RealTime\Default\instant_fluctuations_evaluator.py", line 222, in __init__
    super().__init__(exchange, symbol)
  File "evaluator\RealTime\realtime_evaluator.py", line 91, in __init__
  File "evaluator\RealTime\realtime_evaluator.py", line 109, in _define_refresh_time
KeyError: 'refresh_rate_seconds'
 2018-10-01 23:55:12,635 ERROR    root                   File "start.py", line 183, in <module>
  File "start.py", line 113, in start_octobot
  File "tools\commands.py", line 78, in start_bot
  File "tools\commands.py", line 70, in start_bot
  File "octobot.py", line 159, in create_evaluation_threads
  File "octobot.py", line 175, in _create_symbol_threads_managers
  File "evaluator\evaluator_creator.py", line 87, in create_real_time_ta_evals
  File "C:\Users\greed\Downloads\Trading\test\tentacles\Evaluator\RealTime\Default\instant_fluctuations_evaluator.py", line 222, in __init__
    super().__init__(exchange, symbol)
  File "evaluator\RealTime\realtime_evaluator.py", line 91, in __init__
  File "evaluator\RealTime\realtime_evaluator.py", line 109, in _define_refresh_time
NoneType: None
 2018-10-01 23:55:12,636 ERROR    root                 <class 'KeyError'>: 'refresh_rate_seconds'
NoneType: None
```

**Comment by GuillaumeDSM** [comment]
Hi blizzer3 !
Thanks for your bug report, I found the problem and it should be solved by now.
Re-installing the bot or running the command **OctoBot.exe -p install all** will solve the problem.

Guillaume
