### ISSUE TITLE
OctoBot Exception : Incorrect padding

### ISSUE THREAD

**Issue by mrgreedy911** [Drakkar-Software/OctoBot#412]
* OS : [Windows, Ubuntu, Debian, Raspbian...] 
Windows 10
  * Python Version: _____ (`python -V`)
Python 3.6
  * In case you are not using a binary version:
    * Branch: Master | Dev
    * Last Commit ID: _____ (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
**Describe the bug**
Ran the app after fixing the bug i first reported (my old acc, had to make a new one)
and it starts up but after a while i get this error message and it stops working

  1. Install
  2. I´ve added binance, huobi and cryptopia exchanges 
  3. Then when i press open octobot button it freezes and after a while that bug comes up.

  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:
 
```
 2018-10-02 13:10:07,763 INFO     WebService           Interface successfully initialized and accessible at: http://192.168.10.167:5001.
 2018-10-02 13:10:07,764 DEBUG    Notification         Mail disabled
 2018-10-02 13:10:07,768 DEBUG    Notification         Twitter notification disabled
 2018-10-02 13:10:07,768 DEBUG    Notification         Telegram disabled
 2018-10-02 13:10:08,212 INFO     ExchangeDispatcher - binance online with REST api
 2018-10-02 13:10:22,631 INFO     Trader               Order loaded : BCH/BTC | TraderOrderType.BUY_LIMIT | Price : 0.079623 | Quantity : 0.028 | Status : OrderStatus.OPEN
 2018-10-02 13:10:26,621 INFO     Trader               Order loaded : DASH/BTC | TraderOrderType.BUY_LIMIT | Price : 0.027784 | Quantity : 0.041 | Status : OrderStatus.OPEN
 2018-10-02 13:10:30,151 INFO     Trader               Order loaded : ETC/BTC | TraderOrderType.BUY_LIMIT | Price : 0.001672 | Quantity : 0.96 | Status : OrderStatus.OPEN
 2018-10-02 13:10:59,686 DEBUG    Trader               Enabled on binance
 2018-10-02 13:11:11,195 DEBUG    TraderSimulator      Disabled on binance
 2018-10-02 13:11:11,196 DEBUG    OctoBot              Using DailyTradingMode trading mode
 2018-10-02 13:11:13,029 INFO     ExchangeDispatcher - cryptopia online with REST api
 2018-10-02 13:11:14,201 ERROR    OctoBot Launcher     OctoBot Exception : Incorrect padding
Traceback (most recent call last):
  File "tools\commands.py", line 69, in start_bot
  File "octobot.py", line 110, in create_exchange_traders
  File "trading\trader\trader.py", line 28, in __init__
  File "trading\trader\portfolio.py", line 25, in __init__
  File "trading\trader\portfolio.py", line 43, in _load_portfolio
  File "trading\trader\portfolio.py", line 51, in update_portfolio_balance
  File "trading\exchanges\exchange_dispatcher.py", line 68, in get_balance
  File "trading\exchanges\rest_exchanges\rest_exchange.py", line 120, in get_balance
  File "site-packages\ccxt\cryptopia.py", line 447, in fetch_balance
  File "site-packages\ccxt\base\exchange.py", line 327, in request
  File "site-packages\ccxt\base\exchange.py", line 323, in fetch2
  File "site-packages\ccxt\cryptopia.py", line 687, in sign
  File "base64.py", line 87, in b64decode
binascii.Error: Incorrect padding
 2018-10-02 13:11:14,210 ERROR    root                   File "start.py", line 183, in <module>
  File "start.py", line 113, in start_octobot
  File "tools\commands.py", line 78, in start_bot
  File "tools\commands.py", line 69, in start_bot
  File "octobot.py", line 110, in create_exchange_traders
  File "trading\trader\trader.py", line 28, in __init__
  File "trading\trader\portfolio.py", line 25, in __init__
  File "trading\trader\portfolio.py", line 43, in _load_portfolio
  File "trading\trader\portfolio.py", line 51, in update_portfolio_balance
  File "trading\exchanges\exchange_dispatcher.py", line 68, in get_balance
  File "trading\exchanges\rest_exchanges\rest_exchange.py", line 120, in get_balance
  File "site-packages\ccxt\cryptopia.py", line 447, in fetch_balance
  File "site-packages\ccxt\base\exchange.py", line 327, in request
  File "site-packages\ccxt\base\exchange.py", line 323, in fetch2
  File "site-packages\ccxt\cryptopia.py", line 687, in sign
  File "base64.py", line 87, in b64decode
NoneType: None
 2018-10-02 13:11:14,211 ERROR    root                 <class 'binascii.Error'>: Incorrect padding
NoneType: None
[12064] Failed to execute script start
```

**Comment by GuillaumeDSM** [comment]
Hi mrgreedy911,
We didn't test OctoBot real trading on Cryptopia exchange yet. It should work in theory but we can't confirm it. You can see a list of tested exchanges [here].(https://github.com/Drakkar-Software/OctoBot/wiki/Exchanges#octobot-official-supported-exchanges)
It looks like a problem in the [ccxt library](https://github.com/ccxt/ccxt) Cryptopia interface implementation. We are not planning to further test Cryptopia real trading anytime soon but if you are interested, you can investigate more into the issue and propose a fix. 
Maybe in [ccxt project](https://github.com/ccxt/ccxt) the issue is known and you will be able to easily fix the problem
