### ISSUE TITLE
[Package] OctoBot package can't install and load tentacles module properly

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot#573]
```
2019-01-19 12:12:08,542 INFO     TentaclePackageManager Updating tentacles/Evaluator/evaluator_config.json using new data...
 2019-01-19 12:12:08,551 ERROR    TentaclePackageManager No module named 'tentacles.Evaluator'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tools/tentacle_manager/tentacle_package_manager.py", line 430, in update_evaluator_config_file
    from evaluator.RealTime import RealTimeEvaluator
  File "/usr/local/lib/python3.7/dist-packages/evaluator/RealTime/__init__.py", line 18, in <module>
    from tentacles.Evaluator.RealTime import *
ModuleNotFoundError: No module named 'tentacles.Evaluator'
 2019-01-19 12:12:08,553 ERROR    TentaclePackageManager Something went wrong when checking installed tentacles: No module named 'tentacles.Evaluator'.
If Octobot is now working after this, you should re-install your tentacles (start.py -p install all).
If this problem keeps appearing, try to reset all tentacles (start.py -p reset_tentacles).
 2019-01-19 12:12:08,553 INFO     TentaclePackageManager Updating tentacles/Trading/trading_config.json using new data...
 2019-01-19 12:12:08,722 ERROR    TentaclePackageManager No module named 'tentacles.Evaluator'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tools/tentacle_manager/tentacle_package_manager.py", line 449, in update_trading_config_file
    from trading.trader.modes import AbstractTradingMode
  File "/usr/local/lib/python3.7/dist-packages/trading/trader/modes/__init__.py", line 19, in <module>
    from .abstract_trading_mode import *
  File "/usr/local/lib/python3.7/dist-packages/trading/trader/modes/abstract_trading_mode.py", line 24, in <module>
    from evaluator import Strategies
  File "/usr/local/lib/python3.7/dist-packages/evaluator/Strategies/__init__.py", line 18, in <module>
    from tentacles.Evaluator.Strategies import *
ModuleNotFoundError: No module named 'tentacles.Evaluator'
 2019-01-19 12:12:08,723 ERROR    TentaclePackageManager Something went wrong when checking installed tentacles: No module named 'tentacles.Evaluator'.
If Octobot is now working after this, you should re-install your tentacles (start.py -p install all).
If this problem keeps appearing, try to reset all tentacles (start.py -p reset_tentacl
```es).

**Comment by Herklos** [comment]
Done with https://github.com/Drakkar-Software/OctoBot/pull/608
