### ISSUE TITLE
start on vps?

### ISSUE THREAD

**Issue by minerlab** [Drakkar-Software/OctoBot#592]
can you use it on a linux vps? I try but it gives me error
Octobot-Launcher
INFO: root: Launcher updated
ERROR: LauncherApp: Failed to start tk_app: no display name and no $ DISPLAY environment variable
Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/launcher/app_util.py", line 58, in run
     self.window = Tk ()
   File "/usr/local/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
     self.tk = _tkinter.create (screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $ DISPLAY environment variable

**Comment by Herklos** [comment]
Hi @minerlab. Yes ! You should use OctoBot-Launcher command line interface.

Just use : `Octobot-Launcher --help` to display available commands.

PS : The easiest way to run OctoBot on a VPS is to [use docker](https://github.com/Drakkar-Software/OctoBot/wiki/With-Docker).

**Comment by minerlab** [comment]
hi @Herklos, i used doker but not work 
OctoBot-Launcher -s
INFO:root:Launcher updated
ERROR:LauncherApp:Failed to start tk_app : no display name and no $DISPLAY environment variable
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/launcher/app_util.py", line 58, in run
    self.window = Tk()
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
Traceback (most recent call last):
  File "/usr/local/bin/OctoBot-Launcher", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/entrypoint.py", line 52, in main
    start_launcher(args)
  File "/usr/local/lib/python3.7/site-packages/launcher/launcher_main.py", line 63, in start_launcher
    LauncherApp().start_bot_handler()
  File "/usr/local/lib/python3.7/site-packages/launcher/launcher_app.py", line 146, in start_bot_handler
    self.hide()
  File "/usr/local/lib/python3.7/site-packages/launcher/launcher_app.py", line 213, in hide
    self.window.withdraw()
AttributeError: 'NoneType' object has no attribute 'withdraw'
2019-01-23 16:17:35,716 INFO     OctoBot Launcher     Version : 0.2.4_0-beta2
 2019-01-23 16:17:35,716 INFO     OctoBot Launcher     Loading config files...
 2019-01-23 16:17:35,717 ERROR    CONFIG LOADER        Error when load config file tentacles/Evaluator/evaluator_config.json : file opening failed ([Errno 2] No such file or directory: 'tentacles/Evaluator/evaluator_config.json')
 2019-01-23 16:17:35,717 ERROR    OctoBot Launcher     OctoBot can't start without a valid tentacles/Evaluator/evaluator_config.json configuration file.
This file is generated on tentacle installation using the following command:
start.py -p install all


if i use only -ng this is result

OctoBot-Launcher -ng
INFO:root:Launcher updated

**Comment by Herklos** [comment]
Hi @minerlab, yes it's a good issue, currently starting OctBot from launcher with command line doesn't allow you to use OctoBot's options. I will create an issue to manage this as soon as possible.

Concerning docker, can you explain why it did not work ?

**Comment by minerlab** [comment]
update
not start from pip installation but start whit github clone source, now work!

**Comment by Herklos** [comment]
Ok great ! 

We are currently in beta so we apologize for the problems you may encounter during this development phase. 

I hope you will enjoy our project !

Do not hesitate to join our discord and telegram community.
