### ISSUE TITLE
No module named 'evaluator.Util.advanced_manager'

### ISSUE THREAD

**Issue by LinuxIsCool** [Drakkar-Software/OctoBot#876]
## Step 1: Have you search for this issue before posting it?
Yes I have searched.

## Step 2: Describe your environment
  * Ubuntu 16.04
  * Python Version:3.7.2
  * In case you are not using a binary version:
    * Branch: Master | Dev
 
## Step 3: Describe the problem:
**Describe the bug**
The advanced_manager module is missing in Dev and Master (Fixed on 0.4.0)

**Expected behavior**
Full installation.

### Steps to reproduce:
from: https://github.com/Drakkar-Software/OctoBot/wiki/With-Python-only 

$ git clone https://github.com/Drakkar-Software/OctoBot
$ cd OctoBot
$ cp ./config/default_config.json ./config.json
$ pip3 install -r pre_requirements.txt
$ pip3 install -r requirements.txt
$ python3 start.py -p install all

### Observed Results:

TentaclePackageManager Updating tentacles/Evaluator/evaluator_config.json using new data...
`No module named 'evaluator.Util.advanced_manager'`

### Relevant code exceptions or logs:
 
```
2019-05-08 19:22:35,363 INFO     TentaclePackageManager Updating tentacles/Evaluator/evaluator_config.json using new data...
 2019-05-08 19:22:35,886 ERROR    TentaclePackageManager No module named 'evaluator.Util.advanced_manager'
Traceback (most recent call last):
  File "/home/shawn/.virtualenvs/OctoBot/lib/python3.7/site-packages/tentacles_manager/tentacle_package_manager.py", line 485, in update_evaluator_config_file
    evaluators_in_config)
  File "/home/shawn/.virtualenvs/OctoBot/lib/python3.7/site-packages/tentacles_manager/tentacle_package_util.py", line 179, in update_config_file
    classes_in_config, config_content, classes_list) or changed_something
  File "/home/shawn/.virtualenvs/OctoBot/lib/python3.7/site-packages/tentacles_manager/tentacle_package_util.py", line 201, in add_class_to_config_file_content
    from evaluator.Util.advanced_manager import AdvancedManager
ModuleNotFoundError: No module named 'evaluator.Util.advanced_manager'
 2019-05-08 19:22:35,887 ERROR    TentaclePackageManager Something went wrong when checking installed tentacles: No module named 'evaluator.Util.advanced_manager'.
If Octobot is now working after this, you should re-install your tentacles (start.py -p install all).
If this problem keeps appearing, try to reset all tentacles (start.py -p reset_tentacles).
 2019-05-08 19:22:35,887 INFO     TentaclePackageManager Updating tentacles/Trading/trading_config.json using new data...
 2019-05-08 19:22:35,923 ERROR    TentaclePackageManager No module named 'evaluator.Util.advanced_manager'
Traceback (most recent call last):
  File "/home/shawn/.virtualenvs/OctoBot/lib/python3.7/site-packages/tentacles_manager/tentacle_package_manager.py", line 502, in update_trading_config_file
    trading_modes_in_config)
  File "/home/shawn/.virtualenvs/OctoBot/lib/python3.7/site-packages/tentacles_manager/tentacle_package_util.py", line 179, in update_config_file
    classes_in_config, config_content, classes_list) or changed_something
  File "/home/shawn/.virtualenvs/OctoBot/lib/python3.7/site-packages/tentacles_manager/tentacle_package_util.py", line 201, in add_class_to_config_file_content
    from evaluator.Util.advanced_manager import AdvancedManager
ModuleNotFoundError: No module named 'evaluator.Util.advanced_manager'
 2019-05-08 19:22:35,924 ERROR    TentaclePackageManager Something went wrong when checking installed tentacles: No module named 'evaluator.Util.advanced_manager'.
If Octobot is now working after this, you should re-install your tentacles (start.py -p install all).
If this problem keeps appearing, try to reset all tentacles (start.py -p reset_tentacles).

```

**Comment by GuillaumeDSM** [comment]
Closing this, solved in #878
