### ISSUE TITLE
Update OctoBot fail on MacOS

### ISSUE THREAD

**Issue by dbzalpha** [Drakkar-Software/OctoBot#898]
## Step 1: Have you search for this issue before posting it?
Yes

## Step 2: Describe your environment
  * OS : MacOS 10.13.6 
  * Python Version: 3.7.3, via virtualenv
  * Firefox Browser
 
## Step 3: Describe the problem:
**Describe the bug**
"Update Octobot" doesn't complete through the browser

### Steps to reproduce:

  1. $ virtualenv -p python3.7 venv
  2. $ source venv/bin/activate
  3. python3.7 -m pip install OctoBot
  4. download of launcher_app_osx and paste in $ 
  5. $ chmod +x launcher_app_osx
  6. $ ./launcher_app_osx
  7. interface launched in browser, left part (Octobot) a bit long to load (30s approx.)
  8. click on "Update OctoBot", start to load, then fail and show "This service is temporary unavailable."

### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:
![temporary_unavailable](https://user-images.githubusercontent.com/32240515/57974135-bc692a80-7989-11e9-8c3a-04e1eb3e29cb.png)
 
```
INFO:root:Launcher updated
INFO:root:Launcher fresh install...
INFO:root:Interface successfully initialized and accessible at: http://192.168.15.13:5010
INFO:werkzeug:192.168.15.13 - - [18/May/2019 16:16:31] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.15.13 - - [18/May/2019 16:16:31] "GET /news HTTP/1.1" 200 -
INFO:werkzeug:192.168.15.13 - - [18/May/2019 16:16:32] "GET /launcher HTTP/1.1" 200 -
INFO:werkzeug:192.168.15.13 - - [18/May/2019 16:17:47] "GET /bot HTTP/1.1" 200 -
INFO:root:OctoBot is checking your environment...
INFO:werkzeug:192.168.15.13 - - [18/May/2019 16:17:51] "GET /progress HTTP/1.1" 200 -
INFO:root:Your OctoBot environment is ready !
INFO:root:OctoBot is checking for updates...
INFO:werkzeug:192.168.15.13 - - [18/May/2019 16:17:52] "GET /progress HTTP/1.1" 200 -
INFO:werkzeug:192.168.15.13 - - [18/May/2019 16:18:03] "GET /progress HTTP/1.1" 200 -
ERROR:flask.app:Exception on /install [GET]
Traceback (most recent call last):
  File "flask/app.py", line 2292, in wsgi_app
  File "flask/app.py", line 1815, in full_dispatch_request
  File "flask/app.py", line 1718, in handle_user_exception
  File "flask/_compat.py", line 35, in reraise
  File "flask/app.py", line 1813, in full_dispatch_request
  File "flask/app.py", line 1799, in dispatch_request
  File "/Users/dbecq/code/octobot/launcher/app/app_controller.py", line 68, in install
    launcher_instance.update_bot(launcher_module.bot_instance)
  File "/Users/dbecq/code/octobot/launcher/app/launcher_app.py", line 94, in update_bot
    environment.install_bot(force_package=force_package)
  File "/Users/dbecq/code/octobot/launcher/tools/environment.py", line 96, in install_bot
    update_tentacles(executable_path, force_install=True)
  File "/Users/dbecq/code/octobot/launcher/tools/environment.py", line 140, in update_tentacles
    executor.execute_command_on_current_binary(binary_path, ["-p", "install", "all", "force"])
  File "/Users/dbecq/code/octobot/launcher/tools/executor.py", line 26, in execute_command_on_current_binary
    return subprocess.Popen(cmd, stdout=PIPE).stdout.read().rstrip().decode()
  File "subprocess.py", line 775, in __init__
  File "subprocess.py", line 1522, in _execute_child
OSError: [Errno 8] Exec format error: './OctoBot'
INFO:werkzeug:192.168.15.13 - - [18/May/2019 16:18:03] "GET /install HTTP/1.1" 500 -
```

**Comment by GuillaumeDSM** [comment]
Hello dbzalpha,
For now the binary version is not ready on MacOS platform.
To use OctoBot on MacOS, we recommend following [this process](https://github.com/Drakkar-Software/OctoBot/wiki/With-Python-only)

**Comment by dbzalpha** [comment]
Thanks @GuillaumeDSM, it worked!

**Comment by GuillaumeDSM** [comment]
Great !
