### ISSUE TITLE
Issue with Profitability on Home screen and Portfolio tab doesn't load

### ISSUE THREAD

**Issue by rarunkumar8024** [Drakkar-Software/OctoBot#924]
## Step 3: Describe the problem:
Profitability section from Home screen is not loading. Also, when I click Portfolio tab on the top, the screen doesn't load.  From the logs I see timeout errors.

I ran it against Coinbase Pro exchange.

**Expected behavior**

### Steps to reproduce:

Launch OctoBot using CoinbasePro exchange.  Portfolio page should display the information from CoinbasePro site.

### Observed Results:
Page doesn't load.  Also the profitability section of the Home is blank.  while loading the Home page, it had the same error logs, matches with Portfolio tab load.

### Relevant code exceptions or logs:

2019-06-08 21:56:31 ERROR  asyncio_tools        logging_util.py:62       <coroutine object TradesManager.update_portfolio_and_currencies_current_value at 0x0000013303E4E3C8> coroutine took too long to execute, cancelling the task. (current task before starting this one: None, actual current task before cancel: <Task pending coro=<RealTimeEvaluator.start_task() running at f:\Python\Octobot\OctoBot\evaluator\RealTime\realtime_evaluator.py:92> cb=[gather.<locals>._done_callback() at F:\Python\Octobot\python373\lib\asyncio\tasks.py:664]>)
2019-06-08 21:56:31 ERROR  flask.app            app.py:1780     Exception on /portfolio [GET]
Traceback (most recent call last):
  File "F:\Python\Octobot\python373\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\Python\Octobot\python373\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\Python\Octobot\python373\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Python\Octobot\python373\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "F:\Python\Octobot\python373\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\Python\Octobot\python373\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\Python\Octobot\OctoBot\interfaces\web\controllers\trading.py", line 44, in portfolio
    _, _, portfolio_real_current_value, portfolio_simulated_current_value = get_portfolio_current_value()
  File "f:\Python\Octobot\OctoBot\interfaces\trading_util.py", line 68, in get_portfolio_current_value
    get_bot().run_in_main_asyncio_loop(trade_manager.update_portfolio_and_currencies_current_value())
  File "f:\Python\Octobot\OctoBot\core\octobot.py", line 78, in run_in_main_asyncio_loop
    return self.task_manager.run_in_main_asyncio_loop(coroutine)
  File "f:\Python\Octobot\OctoBot\core\task_manager.py", line 148, in run_in_main_asyncio_loop
    return run_coroutine_in_asyncio_loop(coroutine, self.async_loop)
  File "f:\Python\Octobot\OctoBot\tools\asyncio_tools.py", line 36, in run_coroutine_in_asyncio_loop
    raise e
  File "f:\Python\Octobot\OctoBot\tools\asyncio_tools.py", line 30, in run_coroutine_in_asyncio_loop
    return future.result(DEFAULT_FUTURE_TIMEOUT)
  File "F:\Python\Octobot\python373\lib\concurrent\futures\_base.py", line 434, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by Herklos** [comment]
Hi @rarunkumar8024 ! It's all well known bug that should already be fixed.
What is your current OctoBot version ?

**Comment by rarunkumar8024** [comment]
My version is OctoBot v0.3.5, picked from Dev version

**Comment by GuillaumeDSM** [comment]
Hello !
Can you try this please ?
https://github.com/Drakkar-Software/OctoBot/wiki/Installation-Troubleshoot#octobot-freeze

**Comment by rarunkumar8024** [comment]
Got the same problem after following the steps in the above comment:

2019-06-09 18:18:10 ERROR  flask.app            app.py:1780     Exception on /dashboard/profitability [GET]
Traceback (most recent call last):
  File "F:\Python\Octobot\python373\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\Python\Octobot\python373\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\Python\Octobot\python373\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Python\Octobot\python373\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "F:\Python\Octobot\python373\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\Python\Octobot\python373\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\Python\Octobot\OctoBot\interfaces\web\controllers\dashboard.py", line 56, in profitability
    market_average_profitability = get_global_profitability()
  File "f:\Python\Octobot\OctoBot\interfaces\trading_util.py", line 237, in get_global_profitability
    get_bot().run_in_main_asyncio_loop(trade_manager.get_profitability(with_market=True))
  File "f:\Python\Octobot\OctoBot\core\octobot.py", line 78, in run_in_main_asyncio_loop
    return self.task_manager.run_in_main_asyncio_loop(coroutine)
  File "f:\Python\Octobot\OctoBot\core\task_manager.py", line 148, in run_in_main_asyncio_loop
    return run_coroutine_in_asyncio_loop(coroutine, self.async_loop)
  File "f:\Python\Octobot\OctoBot\tools\asyncio_tools.py", line 36, in run_coroutine_in_asyncio_loop
    raise e
  File "f:\Python\Octobot\OctoBot\tools\asyncio_tools.py", line 30, in run_coroutine_in_asyncio_loop
    return future.result(DEFAULT_FUTURE_TIMEOUT)
  File "F:\Python\Octobot\python373\lib\concurrent\futures\_base.py", line 434, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
2019-06-09 18:18:10 ERROR  TradesManager[coinbasepro] logging_util.py:66       
Traceback (most recent call last):
  File "f:\Python\Octobot\OctoBot\trading\trader\trades_manager.py", line 127, in get_profitability
    await self.update_portfolio_and_currencies_current_value()
  File "f:\Python\Octobot\OctoBot\trading\trader\trades_manager.py", line 201, in update_portfolio_and_currencies_current_value
    self.portfolio_current_value = await self.update_portfolio_current_value(current_portfolio)
  File "f:\Python\Octobot\OctoBot\trading\trader\trades_manager.py", line 267, in update_portfolio_current_value
    self.current_crypto_currencies_values = await self._evaluate_config_crypto_currencies_values()
  File "f:\Python\Octobot\OctoBot\trading\trader\trades_manager.py", line 310, in _evaluate_config_crypto_currencies_values
    values_dict[currency] = await self.evaluate_value(currency, 1)
  File "f:\Python\Octobot\OctoBot\trading\trader\trades_manager.py", line 341, in evaluate_value
    return await self._try_get_value_of_currency(currency, quantity)
  File "f:\Python\Octobot\OctoBot\trading\trader\trades_manager.py", line 282, in _try_get_value_of_currency
    await self._update_currencies_prices(symbol)
  File "f:\Python\Octobot\OctoBot\trading\trader\trades_manager.py", line 111, in _update_currencies_prices
    ticker = await self.exchange.get_price_ticker(symbol)
  File "f:\Python\Octobot\OctoBot\trading\exchanges\exchange_dispatcher.py", line 192, in get_price_ticker
    await self.exchange.get_price_ticker(symbol=symbol)
  File "f:\Python\Octobot\OctoBot\trading\exchanges\rest_exchanges\rest_exchange.py", line 157, in get_price_ticker
    self.get_symbol_data(symbol).update_symbol_ticker(await self.client.fetch_ticker(symbol))
  File "F:\Python\Octobot\python373\lib\site-packages\ccxt\async_support\gdax.py", line 280, in fetch_ticker
    ticker = await self.publicGetProductsIdTicker(request)
  File "F:\Python\Octobot\python373\lib\site-packages\ccxt\async_support\gdax.py", line 781, in request
    response = await self.fetch2(path, api, method, params, headers, body)
  File "F:\Python\Octobot\python373\lib\site-packages\ccxt\async_support\base\exchange.py", line 112, in fetch2
    await self.throttle()
concurrent.futures._base.CancelledError

**Comment by GuillaumeDSM** [comment]
Ok, is the rest of OctoBot still working ? I mean is there still logs about price updater, trades creation etc ?

**Comment by rarunkumar8024** [comment]
Yes, rest of the process continue working.

**Comment by GuillaumeDSM** [comment]
Ok, we will intestigate it, thanks for the details

**Comment by dterg** [comment]
Portfolio also doesn't load here but with no errors whatsoever. Just blank

**Comment by Herklos** [comment]
> Portfolio also doesn't load here but with no errors whatsoever. Just blank

Hi @dterg ! Can you provide more informations ? Because "blank" is really not enough to help you.

- Installation method (python/sources, docker, binary)
- Environment (windows, linux, mac)
- Way to reproduce your issue / what you've made.


Thanks

**Comment by dterg** [comment]
> > Portfolio also doesn't load here but with no errors whatsoever. Just blank
> 
> Hi @dterg ! Can you provide more informations ? Because "blank" is really not enough to help you.
> 
> * Installation method (python/sources, docker, binary)
> * Environment (windows, linux, mac)
> * Way to reproduce your issue / what you've made.
> 
> Thanks

I've cross-tested this on mac OS and Windows. Seems like its actually not a bug (hence why no errors were generated), but when choosing Kraken as the exchange, the portfolio takes a while to load. Bit of patience, and in the end it does load.

**Comment by Herklos** [comment]
> > > Portfolio also doesn't load here but with no errors whatsoever. Just blank
> > 
> > 
> > Hi @dterg ! Can you provide more informations ? Because "blank" is really not enough to help you.
> > 
> > * Installation method (python/sources, docker, binary)
> > * Environment (windows, linux, mac)
> > * Way to reproduce your issue / what you've made.
> > 
> > Thanks
> 
> I've cross-tested this on mac OS and Windows (python 3.7). Seems like its actually not a bug (hence why no errors were generated), but when choosing Kraken as the exchange, the portfolio takes a while to load. Bit of patience, and in the end it does load.

Ok nice to hear. It can be your Internet connection, Kraken lags, or an OctoBot issue. It would be very helpful if you have some additional information / logs to clarify or reproduce this issue.

**Comment by dterg** [comment]
Nothing is logged in the console so not sure where to get additional info. Also nothing in the browser console. Must be API lag(?)

**Comment by Herklos** [comment]
> Nothing is logged in the console so not sure where to get additional info. Also nothing in the browser console. Must be API lag(?)

Yes sometimes Kraken can be very slow. 
You can also take a look at the "logs" folder in the directory, open the file "OctoBot.log" and search for "ERROR".

**Comment by Herklos** [comment]
Closed for no update from owner.
