### ISSUE TITLE
Failed to create order in CoinbasePro

### ISSUE THREAD

**Issue by rarunkumar8024** [Drakkar-Software/OctoBot#926]
## Step 1: Have you search for this issue before posting it? Yes

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/Drakkar-Software/OctoBot/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment: Windows / Python - 3.7.3 / Branch: Dev /  Last Commit Id: c2dea8e
  * OS : [Windows, Ubuntu, Debian, Raspbian...] 
  * Python Version: _____ (`python -V`)
  * In case you are not using a binary version:
    * Branch: Master | Dev
    * Last Commit ID: _____ (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:  CoinbasePro has failed orders due to rounding problems.  Each pair of coins has separate rounding logic and Octobot fails to identify that.  

**Expected behavior**
Each Trading pairs has got both Quote_Increment and Base_Increments defined by CoinbasePro api.  I believe that need to be considered to avoid the errors reported below.

### Steps to reproduce:
Test the pairs like XLM-USD / XRP-USD / ZRX-USD etc to find these kind of issues
  
### Observed Results:

  * Orders are failed 
  * Orders are expected to submit successful

### Relevant code exceptions or logs:

2019-06-09 12:39:49 ERROR  RESTExchange[coinbasepro] logging_util.py:62       Failed to create order : coinbasepro size is too accurate. Smallest unit is 1 (order_type: TraderOrderType.BUY_MARKET, symbol: XRP/BTC, quantity: 20.71613628, price: 4.909e-05, stop_price: None)
2019-06-09 12:39:49 ERROR  RESTExchange[coinbasepro] logging_util.py:66       coinbasepro size is too accurate. Smallest unit is 1
Traceback (most recent call last):
  File "f:\Python\Octobot\OctoBot\trading\exchanges\rest_exchanges\rest_exchange.py", line 217, in create_order
    created_order = await self._create_specific_order(order_type, symbol, quantity, price)
  File "f:\Python\Octobot\OctoBot\trading\exchanges\rest_exchanges\rest_exchange.py", line 243, in _create_specific_order
    created_order = await self.client.create_market_buy_order(symbol, quantity)
  File "F:\Python\Octobot\python373\lib\site-packages\ccxt\async_support\gdax.py", line 532, in create_order
    response = await self.privatePostOrders(self.extend(request, params))
  File "F:\Python\Octobot\python373\lib\site-packages\ccxt\async_support\gdax.py", line 781, in request
    response = await self.fetch2(path, api, method, params, headers, body)
  File "F:\Python\Octobot\python373\lib\site-packages\ccxt\async_support\base\exchange.py", line 115, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "F:\Python\Octobot\python373\lib\site-packages\ccxt\async_support\base\exchange.py", line 163, in fetch
    self.handle_errors(response.status, response.reason, url, method, headers, http_response, json_response)
  File "F:\Python\Octobot\python373\lib\site-packages\ccxt\async_support\gdax.py", line 777, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: coinbasepro size is too accurate. Smallest unit is 1
2019-06-09 12:39:49 INFO   Trader[coinbasepro]  logging_util.py:54       Created order on coinbasepro: None
2019-06-09 12:39:49 ERROR  DailyTradingModeCreator logging_util.py:62       Failed to create order : 'NoneType' object is not subscriptable. Order: XRP/BTC | BUY_MARKET | Price : 4.909e-05 | Quantity : 20.71613628 | Status : OPEN
2019-06-09 12:39:49 ERROR  DailyTradingModeCreator logging_util.py:66       'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "f:\Python\Octobot\OctoBot\tentacles\Trading\Mode\Default\daily_trading_mode.py", line 294, in create_new_order
    await trader.create_order(current_order, portfolio)
  File "f:\Python\Octobot\OctoBot\trading\trader\trader.py", line 196, in create_order
    new_order = await self._create_not_loaded_order(order, new_order, portfolio)
  File "f:\Python\Octobot\OctoBot\trading\trader\trader.py", line 243, in _create_not_loaded_order
    new_order = self.parse_exchange_order_to_order_instance(created_order)
  File "f:\Python\Octobot\OctoBot\trading\trader\trader.py", line 482, in parse_exchange_order_to_order_instance
    return self.create_order_instance(order_type=self.parse_order_type(order),
  File "f:\Python\Octobot\OctoBot\trading\trader\trader.py", line 527, in parse_order_type
    side = TradeOrderSide(order["side"])
TypeError: 'NoneType' object is not subscriptable
-------------------------------------------------------------------

2019-06-09 07:19:19 ERROR  RESTExchange[coinbasepro] logging_util.py:62       Failed to create order : coinbasepro size is too accurate. Smallest unit is 0.00001 (order_type: TraderOrderType.BUY_LIMIT, symbol: ZRX/BTC, quantity: 28.31873563, price: 4.151e-05, stop_price: None)
2019-06-09 07:19:19 ERROR  RESTExchange[coinbasepro] logging_util.py:66       coinbasepro size is too accurate. Smallest unit is 0.00001
Traceback (most recent call last):
  File "f:\Python\Octobot\OctoBot\trading\exchanges\rest_exchanges\rest_exchange.py", line 217, in create_order
    created_order = await self._create_specific_order(order_type, symbol, quantity, price)
  File "f:\Python\Octobot\OctoBot\trading\exchanges\rest_exchanges\rest_exchange.py", line 245, in _create_specific_order
    created_order = await self.client.create_limit_buy_order(symbol, quantity, price)
  File "F:\Python\Octobot\python373\lib\site-packages\ccxt\async_support\gdax.py", line 532, in create_order
    response = await self.privatePostOrders(self.extend(request, params))
  File "F:\Python\Octobot\python373\lib\site-packages\ccxt\async_support\gdax.py", line 781, in request
    response = await self.fetch2(path, api, method, params, headers, body)
  File "F:\Python\Octobot\python373\lib\site-packages\ccxt\async_support\base\exchange.py", line 115, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "F:\Python\Octobot\python373\lib\site-packages\ccxt\async_support\base\exchange.py", line 163, in fetch
    self.handle_errors(response.status, response.reason, url, method, headers, http_response, json_response)
  File "F:\Python\Octobot\python373\lib\site-packages\ccxt\async_support\gdax.py", line 777, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: coinbasepro size is too accurate. Smallest unit is 0.00001
2019-06-09 07:19:19 INFO   Trader[coinbasepro]  logging_util.py:54       Created order on coinbasepro: None
2019-06-09 07:19:19 ERROR  DailyTradingModeCreator logging_util.py:62       Failed to create order : 'NoneType' object is not subscriptable. Order: ZRX/BTC | BUY_LIMIT | Price : 4.151e-05 | Quantity : 28.31873563 | Status : OPEN
2019-06-09 07:19:19 ERROR  DailyTradingModeCreator logging_util.py:66       'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "f:\Python\Octobot\OctoBot\tentacles\Trading\Mode\Default\daily_trading_mode.py", line 277, in create_new_order
    await trader.create_order(current_order, portfolio)
  File "f:\Python\Octobot\OctoBot\trading\trader\trader.py", line 196, in create_order
    new_order = await self._create_not_loaded_order(order, new_order, portfolio)
  File "f:\Python\Octobot\OctoBot\trading\trader\trader.py", line 243, in _create_not_loaded_order
    new_order = self.parse_exchange_order_to_order_instance(created_order)
  File "f:\Python\Octobot\OctoBot\trading\trader\trader.py", line 482, in parse_exchange_order_to_order_instance
    return self.create_order_instance(order_type=self.parse_order_type(order),
  File "f:\Python\Octobot\OctoBot\trading\trader\trader.py", line 527, in parse_order_type
    side = TradeOrderSide(order["side"])
TypeError: 'NoneType' object is not subscriptable

**Comment by Herklos** [comment]
Hi @rarunkumar8024 ! 
Thanks for reporting some issues.
Similar to https://github.com/Drakkar-Software/OctoBot/issues/297
