### ISSUE TITLE
Deribit Integration Crashes Octobot

### ISSUE THREAD

**Issue by stuxfred** [Drakkar-Software/OctoBot#935]
: Describe your environment
  * OS : UBUNTU
  * Python Version: 3.7
 
When I add Deribit and leave the api credentials on default or customized Octobot fails to start and crashes.
Logs:
2019-07-02 13:38:37,186 ERROR    OctoBot Launcher     OctoBot Exception : argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/root/OctoBot/tools/commands.py", line 110, in start_bot
    await bot.initialize()
  File "/root/OctoBot/core/octobot.py", line 68, in initialize
    await self.exchange_factory.create()
  File "/root/OctoBot/core/exchange_factory.py", line 58, in create
    await self._create_exchange_traders(exchange_class_string)
  File "/root/OctoBot/core/exchange_factory.py", line 79, in _create_exchange_traders
    await exchange_manager.initialize()
  File "/root/OctoBot/tools/initializable.py", line 28, in initialize
    await self.initialize_impl()
  File "/root/OctoBot/trading/exchanges/exchange_manager.py", line 63, in initialize_impl
    await self.create_exchanges()
  File "/root/OctoBot/trading/exchanges/exchange_manager.py", line 88, in create_exchanges
    self._load_constants()
  File "/root/OctoBot/trading/exchanges/exchange_manager.py", line 73, in _load_constants
    self._set_config_time_frame()
  File "/root/OctoBot/trading/exchanges/exchange_manager.py", line 244, in _set_config_time_frame
    if self.time_frame_exists(time_frame.value):
  File "/root/OctoBot/trading/exchanges/exchange_manager.py", line 259, in time_frame_exists
    return time_frame in self.client_time_frames[CONFIG_WILDCARD]
TypeError: argument of type 'NoneType' is not iterable
 2019-07-02 13:38:37,191 ERROR    root                   File "start.py", line 286, in <module>
    main()
  File "start.py", line 282, in main
    start_octobot(args)
  File "start.py", line 190, in start_octobot
    asyncio.run(Commands.start_bot(bot, logger), debug=debug_mode)
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/root/OctoBot/tools/commands.py", line 122, in start_bot
    raise e
  File "/root/OctoBot/tools/commands.py", line 110, in start_bot
    await bot.initialize()
  File "/root/OctoBot/core/octobot.py", line 68, in initialize
    await self.exchange_factory.create()
  File "/root/OctoBot/core/exchange_factory.py", line 58, in create
    await self._create_exchange_traders(exchange_class_string)
  File "/root/OctoBot/core/exchange_factory.py", line 79, in _create_exchange_traders
    await exchange_manager.initialize()
  File "/root/OctoBot/tools/initializable.py", line 28, in initialize
    await self.initialize_impl()
  File "/root/OctoBot/trading/exchanges/exchange_manager.py", line 63, in initialize_impl
    await self.create_exchanges()
  File "/root/OctoBot/trading/exchanges/exchange_manager.py", line 88, in create_exchanges
    self._load_constants()
  File "/root/OctoBot/trading/exchanges/exchange_manager.py", line 73, in _load_constants
    self._set_config_time_frame()
  File "/root/OctoBot/trading/exchanges/exchange_manager.py", line 244, in _set_config_time_frame
    if self.time_frame_exists(time_frame.value):
  File "/root/OctoBot/trading/exchanges/exchange_manager.py", line 259, in time_frame_exists
    return time_frame in self.client_time_frames[CONFIG_WILDCARD]
NoneType: None
 2019-07-02 13:38:37,193 ERROR    root                 <class 'TypeError'>: argument of type 'NoneType' is not iterable
NoneType: None

**Comment by Herklos** [comment]
Hi @stuxfred ! Did you put a wildcard (*) in your cryptocurrencies config ?
